site_name: FogApi
nav:
  - Home: index.md
  - About: about_FogApi.md
  - Release Notes: ReleaseNotes.md
  - Commands: 
    - 'Index': 'commands/index.md'
    - 'Add-FogHostMac': 'commands/Add-FogHostMac.md'
    - 'Add-FogResultData': 'commands/Add-FogResultData.md'
    - 'Approve-FogPendingMac': 'commands/Approve-FogPendingMac.md'
    - 'Deny-FogPendingMac': 'commands/Deny-FogPendingMac.md'
    - 'Find-FogObject': 'commands/Find-FogObject.md'
    - 'Get-FogActiveTasks': 'commands/Get-FogActiveTasks.md'
    - 'Get-FogAssociatedSnapins': 'commands/Get-FogAssociatedSnapins.md'
    - 'Get-FogGroupAssociations': 'commands/Get-FogGroupAssociations.md'
    - 'Get-FogGroupByName': 'commands/Get-FogGroupByName.md'
    - 'Get-FogGroups': 'commands/Get-FogGroups.md'
    - 'Get-FogHost': 'commands/Get-FogHost.md'
    - 'Get-FogHostGroup': 'commands/Get-FogHostGroup.md'
    - 'Get-FogHostMacs': 'commands/Get-FogHostMacs.md'
    - 'Get-FogHostPendingMacs': 'commands/Get-FogHostPendingMacs.md'
    - 'Get-FogHosts': 'commands/Get-FogHosts.md'
    - 'Get-FogImages': 'commands/Get-FogImages.md'
    - 'Get-FogInventory': 'commands/Get-FogInventory.md'
    - 'Get-FogLog': 'commands/Get-FogLog.md'
    - 'Get-FogMacAddresses': 'commands/Get-FogMacAddresses.md'
    - 'Get-FogModules': 'commands/Get-FogModules.md'
    - 'Get-FogObject': 'commands/Get-FogObject.md'
    - 'Get-FogSecsSinceEpoch': 'commands/Get-FogSecsSinceEpoch.md'
    - 'Get-FogServerSettings': 'commands/Get-FogServerSettings.md'
    - 'Get-FogServerSettingsFile': 'commands/Get-FogServerSettingsFile.md'
    - 'Get-FogSnapins': 'commands/Get-FogSnapins.md'
    - 'Get-LastImageTime': 'commands/Get-LastImageTime.md'
    - 'Install-FogService': 'commands/Install-FogService.md'
    - 'Invoke-FogApi': 'commands/Invoke-FogApi.md'
    - 'New-FogHost': 'commands/New-FogHost.md'
    - 'New-FogObject': 'commands/New-FogObject.md'
    - 'Receive-FogImage': 'commands/Receive-FogImage.md'
    - 'Remove-FogObject': 'commands/Remove-FogObject.md'
    - 'Remove-UsbMac': 'commands/Remove-UsbMac.md'
    - 'Reset-HostEncryption': 'commands/Reset-HostEncryption.md'
    - 'Resolve-HostID': 'commands/Resolve-HostID.md'
    - 'Send-FogImage': 'commands/Send-FogImage.md'
    - 'Set-FogInventory': 'commands/Set-FogInventory.md'
    - 'Set-FogServerSettings': 'commands/Set-FogServerSettings.md'
    - 'Set-FogServerSettingsFileSecurity': 'commands/Set-FogServerSettingsFileSecurity.md'
    - 'Set-FogSnapins': 'commands/Set-FogSnapins.md'
    - 'Start-FogSnapin': 'commands/Start-FogSnapin.md'
    - 'Start-FogSnapins': 'commands/Start-FogSnapins.md'
    - 'Update-FogObject': 'commands/Update-FogObject.md'

theme: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
