site_name: FogApi
site_url: https://fogapi.readthedocs.io/en/latest/
site_author: JJ Fullmer
site_description: >- 
  Documentation for the powershell module for using the Fog Project api for various use cases
# Repository 
repo_name: Darksidemilk/fogApi
repo_url: https://github.com/darksidemilk/fogApi 
 
copyright: Copyright &copy; 2018 - 2023 JJ Fullmer


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  favicon: assets/favicon.png
  logo: assets/favicon.png
  icon:
    logo: logo
 
plugins: 
  - search 
  - include_dir_to_nav # see also https://pypi.org/project/mkdocs-include-dir-to-nav/ this allows for an auto organized site map 
  # - roamlinks # added for support of obsidian see also https://about.gitlab.com/blog/2022/03/15/publishing-obsidian-notes-with-gitlab-pages/ and https://github.com/Jackiexiao/mkdocs-roamlinks-plugin 
  # - callouts   
 # Extensions 
markdown_extensions: 
  - abbr
  - admonition 
  - attr_list 
  - def_list 
  - footnotes 
  - md_in_html 
  - pymdownx.highlight 
  - pymdownx.superfences 
  - pymdownx.details 
  - pymdownx.magiclink 
  - nl2br 
  - pymdownx.tasklist 
  - pymdownx.emoji: 
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg 
  - tables # see also https://squidfunk.github.io/mkdocs-material/reference/data-tables/ 
  - toc: 
      permalink: true

nav:
  - Home: index.md
  - About: about_FogApi.md
  - Release Notes: ReleaseNotes.md
  - Commands: 
    - 'Index': 'commands/index.md'
    - commands

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
