site_name: FogApi
nav:
  - Home: index.md
  - About: about_FogApi.md
  - Release Notes: ReleaseNotes.md
  - Commands: 
    - 'Index': 'commands/index.md'
    - 'Add-FogHostMac': 'commands/Add-FogHostMac.md'
    - 'Approve-FogPendingMac': 'commands/Approve-FogPendingMac.md'
    - 'Deny-FogPendingMac': 'commands/Deny-FogPendingMac.md'
    - 'Get-FogActiveTasks': 'commands/Get-FogActiveTasks.md'
    - 'Get-FogAssociatedSnapins': 'commands/Get-FogAssociatedSnapins.md'
    - 'Get-FogGroup': 'commands/Get-FogGroup.md'
    - 'Get-FogHost': 'commands/Get-FogHost.md'
    - 'Get-FogHosts': 'commands/Get-FogHosts.md'
    - 'Get-FogInventory': 'commands/Get-FogInventory.md'
    - 'Get-FogLog': 'commands/Get-FogLog.md'
    - 'Get-FogObject': 'commands/Get-FogObject.md'
    - 'Get-FogServerSettings': 'commands/Get-FogServerSettings.md'
    - 'Get-FogSnapins': 'commands/Get-FogSnapins.md'
    - 'Get-PendingMacsForHost': 'commands/Get-PendingMacsForHost.md'
    - 'Install-FogService': 'commands/Install-FogService.md'
    - 'Invoke-FogApi': 'commands/Invoke-FogApi.md'
    - 'New-FogObject': 'commands/New-FogObject.md'
    - 'Remove-FogObject': 'commands/Remove-FogObject.md'
    - 'Remove-UsbMac': 'commands/Remove-UsbMac.md'
    - 'Reset-HostEncryption': 'commands/Reset-HostEncryption.md'
    - 'Set-FogInventory': 'commands/Set-FogInventory.md'
    - 'Set-FogServerSettings': 'commands/Set-FogServerSettings.md'
    - 'Set-FogSnapins': 'commands/Set-FogSnapins.md'
    - 'Start-FogSnapins': 'commands/Start-FogSnapins.md'
    - 'Update-FogObject': 'commands/Update-FogObject.md'

theme: readthedocs
