#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogGroupApi' {
    Context 'Stop-FogGroup' {
        It 'Test Stop-FogGroup' {
            #$TestResult = Stop-FogGroup -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogCountGroup' {
        It 'Test Invoke-FogCountGroup' {
            #$TestResult = Invoke-FogCountGroup -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogGroup' {
        It 'Test New-FogGroup' {
            #$TestResult = New-FogGroup -Group "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeleteGroup' {
        It 'Test Invoke-FogDeleteGroup' {
            #$TestResult = Invoke-FogDeleteGroup -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsGroup' {
        It 'Test Invoke-FogIdsGroup' {
            #$TestResult = Invoke-FogIdsGroup -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivGroup' {
        It 'Test ConvertTo-FogdivGroup' {
            #$TestResult = ConvertTo-FogdivGroup -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogByNameGroup' {
        It 'Test Join-FogByNameGroup' {
            #$TestResult = Join-FogByNameGroup -JoinByNameGroupRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogGroup' {
        It 'Test Join-FogGroup' {
            #$TestResult = Join-FogGroup -JoinGroupRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListGroup' {
        It 'Test Invoke-FogListGroup' {
            #$TestResult = Invoke-FogListGroup -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsGroup' {
        It 'Test Move-FogsGroup' {
            #$TestResult = Move-FogsGroup -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Search-FogGroup' {
        It 'Test Search-FogGroup' {
            #$TestResult = Search-FogGroup -Item "TEST_VALUE" -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogTaskGroup' {
        It 'Test Invoke-FogTaskGroup' {
            #$TestResult = Invoke-FogTaskGroup -Id "TEST_VALUE" -TaskFiledeletequeueRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogGroup' {
        It 'Test Update-FogGroup' {
            #$TestResult = Update-FogGroup -Id "TEST_VALUE" -Group "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
