#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogGroupassociationApi' {
    Context 'Invoke-FogCountGroupassociation' {
        It 'Test Invoke-FogCountGroupassociation' {
            #$TestResult = Invoke-FogCountGroupassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogGroupassociation' {
        It 'Test New-FogGroupassociation' {
            #$TestResult = New-FogGroupassociation -Groupassociation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeleteGroupassociation' {
        It 'Test Invoke-FogDeleteGroupassociation' {
            #$TestResult = Invoke-FogDeleteGroupassociation -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsGroupassociation' {
        It 'Test Invoke-FogIdsGroupassociation' {
            #$TestResult = Invoke-FogIdsGroupassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivGroupassociation' {
        It 'Test ConvertTo-FogdivGroupassociation' {
            #$TestResult = ConvertTo-FogdivGroupassociation -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogGroupassociation' {
        It 'Test Join-FogGroupassociation' {
            #$TestResult = Join-FogGroupassociation -JoinGroupassociationRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListGroupassociation' {
        It 'Test Invoke-FogListGroupassociation' {
            #$TestResult = Invoke-FogListGroupassociation -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsGroupassociation' {
        It 'Test Move-FogsGroupassociation' {
            #$TestResult = Move-FogsGroupassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogGroupassociation' {
        It 'Test Update-FogGroupassociation' {
            #$TestResult = Update-FogGroupassociation -Id "TEST_VALUE" -Groupassociation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
