#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogHostscreensettingApi' {
    Context 'Invoke-FogCountHostscreensetting' {
        It 'Test Invoke-FogCountHostscreensetting' {
            #$TestResult = Invoke-FogCountHostscreensetting -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogHostscreensetting' {
        It 'Test New-FogHostscreensetting' {
            #$TestResult = New-FogHostscreensetting -Hostscreensetting "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeleteHostscreensetting' {
        It 'Test Invoke-FogDeleteHostscreensetting' {
            #$TestResult = Invoke-FogDeleteHostscreensetting -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsHostscreensetting' {
        It 'Test Invoke-FogIdsHostscreensetting' {
            #$TestResult = Invoke-FogIdsHostscreensetting -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivHostscreensetting' {
        It 'Test ConvertTo-FogdivHostscreensetting' {
            #$TestResult = ConvertTo-FogdivHostscreensetting -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogHostscreensetting' {
        It 'Test Join-FogHostscreensetting' {
            #$TestResult = Join-FogHostscreensetting -JoinHostscreensettingRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListHostscreensetting' {
        It 'Test Invoke-FogListHostscreensetting' {
            #$TestResult = Invoke-FogListHostscreensetting -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsHostscreensetting' {
        It 'Test Move-FogsHostscreensetting' {
            #$TestResult = Move-FogsHostscreensetting -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogHostscreensetting' {
        It 'Test Update-FogHostscreensetting' {
            #$TestResult = Update-FogHostscreensetting -Id "TEST_VALUE" -Hostscreensetting "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
