#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogImageApi' {
    Context 'Invoke-FogCountImage' {
        It 'Test Invoke-FogCountImage' {
            #$TestResult = Invoke-FogCountImage -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogImage' {
        It 'Test New-FogImage' {
            #$TestResult = New-FogImage -Image "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeleteImage' {
        It 'Test Invoke-FogDeleteImage' {
            #$TestResult = Invoke-FogDeleteImage -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsImage' {
        It 'Test Invoke-FogIdsImage' {
            #$TestResult = Invoke-FogIdsImage -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivImage' {
        It 'Test ConvertTo-FogdivImage' {
            #$TestResult = ConvertTo-FogdivImage -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogImage' {
        It 'Test Join-FogImage' {
            #$TestResult = Join-FogImage -JoinImageRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListImage' {
        It 'Test Invoke-FogListImage' {
            #$TestResult = Invoke-FogListImage -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsImage' {
        It 'Test Move-FogsImage' {
            #$TestResult = Move-FogsImage -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Search-FogImage' {
        It 'Test Search-FogImage' {
            #$TestResult = Search-FogImage -Item "TEST_VALUE" -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogImage' {
        It 'Test Update-FogImage' {
            #$TestResult = Update-FogImage -Id "TEST_VALUE" -Image "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
