#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogLdapusergrantApi' {
    Context 'Invoke-FogCountLdapusergrant' {
        It 'Test Invoke-FogCountLdapusergrant' {
            #$TestResult = Invoke-FogCountLdapusergrant -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogLdapusergrant' {
        It 'Test New-FogLdapusergrant' {
            #$TestResult = New-FogLdapusergrant -Ldapusergrant "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeleteLdapusergrant' {
        It 'Test Invoke-FogDeleteLdapusergrant' {
            #$TestResult = Invoke-FogDeleteLdapusergrant -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsLdapusergrant' {
        It 'Test Invoke-FogIdsLdapusergrant' {
            #$TestResult = Invoke-FogIdsLdapusergrant -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivLdapusergrant' {
        It 'Test ConvertTo-FogdivLdapusergrant' {
            #$TestResult = ConvertTo-FogdivLdapusergrant -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogLdapusergrant' {
        It 'Test Join-FogLdapusergrant' {
            #$TestResult = Join-FogLdapusergrant -JoinLdapusergrantRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListLdapusergrant' {
        It 'Test Invoke-FogListLdapusergrant' {
            #$TestResult = Invoke-FogListLdapusergrant -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsLdapusergrant' {
        It 'Test Move-FogsLdapusergrant' {
            #$TestResult = Move-FogsLdapusergrant -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Search-FogLdapusergrant' {
        It 'Test Search-FogLdapusergrant' {
            #$TestResult = Search-FogLdapusergrant -Item "TEST_VALUE" -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogLdapusergrant' {
        It 'Test Update-FogLdapusergrant' {
            #$TestResult = Update-FogLdapusergrant -Id "TEST_VALUE" -Ldapusergrant "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
