#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogMacaddressassociationApi' {
    Context 'Invoke-FogCountMacaddressassociation' {
        It 'Test Invoke-FogCountMacaddressassociation' {
            #$TestResult = Invoke-FogCountMacaddressassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogMacaddressassociation' {
        It 'Test New-FogMacaddressassociation' {
            #$TestResult = New-FogMacaddressassociation -Macaddressassociation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeleteMacaddressassociation' {
        It 'Test Invoke-FogDeleteMacaddressassociation' {
            #$TestResult = Invoke-FogDeleteMacaddressassociation -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsMacaddressassociation' {
        It 'Test Invoke-FogIdsMacaddressassociation' {
            #$TestResult = Invoke-FogIdsMacaddressassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivMacaddressassociation' {
        It 'Test ConvertTo-FogdivMacaddressassociation' {
            #$TestResult = ConvertTo-FogdivMacaddressassociation -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogMacaddressassociation' {
        It 'Test Join-FogMacaddressassociation' {
            #$TestResult = Join-FogMacaddressassociation -JoinMacaddressassociationRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListMacaddressassociation' {
        It 'Test Invoke-FogListMacaddressassociation' {
            #$TestResult = Invoke-FogListMacaddressassociation -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsMacaddressassociation' {
        It 'Test Move-FogsMacaddressassociation' {
            #$TestResult = Move-FogsMacaddressassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogMacaddressassociation' {
        It 'Test Update-FogMacaddressassociation' {
            #$TestResult = Update-FogMacaddressassociation -Id "TEST_VALUE" -Macaddressassociation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
