#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogPxemenuoptionsApi' {
    Context 'Invoke-FogCountPxemenuoptions' {
        It 'Test Invoke-FogCountPxemenuoptions' {
            #$TestResult = Invoke-FogCountPxemenuoptions -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogPxemenuoptions' {
        It 'Test New-FogPxemenuoptions' {
            #$TestResult = New-FogPxemenuoptions -Pxemenuoptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeletePxemenuoptions' {
        It 'Test Invoke-FogDeletePxemenuoptions' {
            #$TestResult = Invoke-FogDeletePxemenuoptions -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsPxemenuoptions' {
        It 'Test Invoke-FogIdsPxemenuoptions' {
            #$TestResult = Invoke-FogIdsPxemenuoptions -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivPxemenuoptions' {
        It 'Test ConvertTo-FogdivPxemenuoptions' {
            #$TestResult = ConvertTo-FogdivPxemenuoptions -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogPxemenuoptions' {
        It 'Test Join-FogPxemenuoptions' {
            #$TestResult = Join-FogPxemenuoptions -JoinPxemenuoptionsRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListPxemenuoptions' {
        It 'Test Invoke-FogListPxemenuoptions' {
            #$TestResult = Invoke-FogListPxemenuoptions -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsPxemenuoptions' {
        It 'Test Move-FogsPxemenuoptions' {
            #$TestResult = Move-FogsPxemenuoptions -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Search-FogPxemenuoptions' {
        It 'Test Search-FogPxemenuoptions' {
            #$TestResult = Search-FogPxemenuoptions -Item "TEST_VALUE" -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogPxemenuoptions' {
        It 'Test Update-FogPxemenuoptions' {
            #$TestResult = Update-FogPxemenuoptions -Id "TEST_VALUE" -Pxemenuoptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
