#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogPrinterassociationApi' {
    Context 'Invoke-FogCountPrinterassociation' {
        It 'Test Invoke-FogCountPrinterassociation' {
            #$TestResult = Invoke-FogCountPrinterassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogPrinterassociation' {
        It 'Test New-FogPrinterassociation' {
            #$TestResult = New-FogPrinterassociation -Printerassociation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeletePrinterassociation' {
        It 'Test Invoke-FogDeletePrinterassociation' {
            #$TestResult = Invoke-FogDeletePrinterassociation -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsPrinterassociation' {
        It 'Test Invoke-FogIdsPrinterassociation' {
            #$TestResult = Invoke-FogIdsPrinterassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivPrinterassociation' {
        It 'Test ConvertTo-FogdivPrinterassociation' {
            #$TestResult = ConvertTo-FogdivPrinterassociation -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogPrinterassociation' {
        It 'Test Join-FogPrinterassociation' {
            #$TestResult = Join-FogPrinterassociation -JoinPrinterassociationRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListPrinterassociation' {
        It 'Test Invoke-FogListPrinterassociation' {
            #$TestResult = Invoke-FogListPrinterassociation -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsPrinterassociation' {
        It 'Test Move-FogsPrinterassociation' {
            #$TestResult = Move-FogsPrinterassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogPrinterassociation' {
        It 'Test Update-FogPrinterassociation' {
            #$TestResult = Update-FogPrinterassociation -Id "TEST_VALUE" -Printerassociation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
