#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogPrinterApi' {
    Context 'Invoke-FogCountPrinter' {
        It 'Test Invoke-FogCountPrinter' {
            #$TestResult = Invoke-FogCountPrinter -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogPrinter' {
        It 'Test New-FogPrinter' {
            #$TestResult = New-FogPrinter -Printer "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeletePrinter' {
        It 'Test Invoke-FogDeletePrinter' {
            #$TestResult = Invoke-FogDeletePrinter -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsPrinter' {
        It 'Test Invoke-FogIdsPrinter' {
            #$TestResult = Invoke-FogIdsPrinter -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivPrinter' {
        It 'Test ConvertTo-FogdivPrinter' {
            #$TestResult = ConvertTo-FogdivPrinter -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogPrinter' {
        It 'Test Join-FogPrinter' {
            #$TestResult = Join-FogPrinter -JoinPrinterRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListPrinter' {
        It 'Test Invoke-FogListPrinter' {
            #$TestResult = Invoke-FogListPrinter -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsPrinter' {
        It 'Test Move-FogsPrinter' {
            #$TestResult = Move-FogsPrinter -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Search-FogPrinter' {
        It 'Test Search-FogPrinter' {
            #$TestResult = Search-FogPrinter -Item "TEST_VALUE" -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogPrinter' {
        It 'Test Update-FogPrinter' {
            #$TestResult = Update-FogPrinter -Id "TEST_VALUE" -Printer "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
