#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogFogSnapinassociationApi' {
    Context 'Invoke-FogCountSnapinassociation' {
        It 'Test Invoke-FogCountSnapinassociation' {
            #$TestResult = Invoke-FogCountSnapinassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-FogSnapinassociation' {
        It 'Test New-FogSnapinassociation' {
            #$TestResult = New-FogSnapinassociation -Snapinassociation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogDeleteSnapinassociation' {
        It 'Test Invoke-FogDeleteSnapinassociation' {
            #$TestResult = Invoke-FogDeleteSnapinassociation -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogIdsSnapinassociation' {
        It 'Test Invoke-FogIdsSnapinassociation' {
            #$TestResult = Invoke-FogIdsSnapinassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'ConvertTo-FogdivSnapinassociation' {
        It 'Test ConvertTo-FogdivSnapinassociation' {
            #$TestResult = ConvertTo-FogdivSnapinassociation -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-FogSnapinassociation' {
        It 'Test Join-FogSnapinassociation' {
            #$TestResult = Join-FogSnapinassociation -JoinSnapinassociationRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-FogListSnapinassociation' {
        It 'Test Invoke-FogListSnapinassociation' {
            #$TestResult = Invoke-FogListSnapinassociation -Start "TEST_VALUE" -Length "TEST_VALUE" -Expand "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-FogsSnapinassociation' {
        It 'Test Move-FogsSnapinassociation' {
            #$TestResult = Move-FogsSnapinassociation -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-FogSnapinassociation' {
        It 'Test Update-FogSnapinassociation' {
            #$TestResult = Update-FogSnapinassociation -Id "TEST_VALUE" -Snapinassociation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
