#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Responses may carry computed fields that are not columns and are not settable through the generic create/edit path: hosts.

.PARAMETER Id
No description available.
.PARAMETER Name
No description available.
.PARAMETER Description
No description available.
.PARAMETER Building
No description available.
.PARAMETER Kernel
No description available.
.PARAMETER KernelArgs
No description available.
.PARAMETER KernelDevice
No description available.
.PARAMETER Init
No description available.
.OUTPUTS

Group<PSCustomObject>
#>

function Initialize-FogGroup {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Building} = 0,
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Kernel},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${KernelArgs},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${KernelDevice},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Init}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogGroup' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($Name.length -gt 50) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 50."
        }

        if (!$Kernel -and $Kernel.length -gt 255) {
            throw "invalid value for 'Kernel', the character length must be smaller than or equal to 255."
        }

        if (!$KernelArgs -and $KernelArgs.length -gt 255) {
            throw "invalid value for 'KernelArgs', the character length must be smaller than or equal to 255."
        }

        if (!$KernelDevice -and $KernelDevice.length -gt 255) {
            throw "invalid value for 'KernelDevice', the character length must be smaller than or equal to 255."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'description' = ${Description}
            'building' = ${Building}
            'kernel' = ${Kernel}
            'kernelArgs' = ${KernelArgs}
            'kernelDevice' = ${KernelDevice}
            'init' = ${Init}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Group<PSCustomObject>

.DESCRIPTION

Convert from JSON to Group<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Group<PSCustomObject>
#>
function ConvertFrom-FogJsonToGroup {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogGroup' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogGroup
        $AllProperties = ('id', 'name', 'description', 'building', 'kernel', 'kernelArgs', 'kernelDevice', 'init')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'description'))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties['description'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'building'))) { #optional property not found
            $Building = $null
        } else {
            $Building = $JsonParameters.PSobject.Properties['building'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'kernel'))) { #optional property not found
            $Kernel = $null
        } else {
            $Kernel = $JsonParameters.PSobject.Properties['kernel'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'kernelArgs'))) { #optional property not found
            $KernelArgs = $null
        } else {
            $KernelArgs = $JsonParameters.PSobject.Properties['kernelArgs'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'kernelDevice'))) { #optional property not found
            $KernelDevice = $null
        } else {
            $KernelDevice = $JsonParameters.PSobject.Properties['kernelDevice'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'init'))) { #optional property not found
            $Init = $null
        } else {
            $Init = $JsonParameters.PSobject.Properties['init'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'description' = ${Description}
            'building' = ${Building}
            'kernel' = ${Kernel}
            'kernelArgs' = ${KernelArgs}
            'kernelDevice' = ${KernelDevice}
            'init' = ${Init}
        }

        return $PSO
    }

}

