#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Responses may carry computed fields that are not columns and are not settable through the generic create/edit path: image, storagegroup.

.PARAMETER Id
No description available.
.PARAMETER ImageID
No description available.
.PARAMETER StoragegroupID
No description available.
.PARAMETER Primary
No description available.
.PARAMETER Image
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Storagegroup
Computed field. Returned by the API but not a column, and not settable.
.OUTPUTS

Imageassociation<PSCustomObject>
#>

function Initialize-FogImageassociation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${ImageID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${StoragegroupID},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${Primary} = "0",
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Image},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Storagegroup}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogImageassociation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ImageID) {
            throw "invalid value for 'ImageID', 'ImageID' cannot be null."
        }

        if ($null -eq $StoragegroupID) {
            throw "invalid value for 'StoragegroupID', 'StoragegroupID' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'imageID' = ${ImageID}
            'storagegroupID' = ${StoragegroupID}
            'primary' = ${Primary}
            'image' = ${Image}
            'storagegroup' = ${Storagegroup}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Imageassociation<PSCustomObject>

.DESCRIPTION

Convert from JSON to Imageassociation<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Imageassociation<PSCustomObject>
#>
function ConvertFrom-FogJsonToImageassociation {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogImageassociation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FogImageassociationAdditionalProperties = @{}

        # check if Json contains properties not defined in FogImageassociation
        $AllProperties = ('id', 'imageID', 'storagegroupID', 'primary', 'image', 'storagegroup')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FogImageassociationAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'imageID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'imageID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'imageID' missing."
        } else {
            $ImageID = $JsonParameters.PSobject.Properties['imageID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'storagegroupID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'storagegroupID' missing."
        } else {
            $StoragegroupID = $JsonParameters.PSobject.Properties['storagegroupID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'primary'))) { #optional property not found
            $Primary = $null
        } else {
            $Primary = $JsonParameters.PSobject.Properties['primary'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'image'))) { #optional property not found
            $Image = $null
        } else {
            $Image = $JsonParameters.PSobject.Properties['image'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'storagegroup'))) { #optional property not found
            $Storagegroup = $null
        } else {
            $Storagegroup = $JsonParameters.PSobject.Properties['storagegroup'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'imageID' = ${ImageID}
            'storagegroupID' = ${StoragegroupID}
            'primary' = ${Primary}
            'image' = ${Image}
            'storagegroup' = ${Storagegroup}
            'AdditionalProperties' = $FogImageassociationAdditionalProperties
        }

        return $PSO
    }

}

