#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No type information available for this column.
.PARAMETER Name
No type information available for this column.
.PARAMETER Description
No type information available for this column.
.PARAMETER Address
No type information available for this column.
.PARAMETER Port
No type information available for this column.
.PARAMETER SearchDN
No type information available for this column.
.PARAMETER UserNamAttr
No type information available for this column.
.PARAMETER GrpNamAttr
No type information available for this column.
.PARAMETER GrpMemberAttr
No type information available for this column.
.PARAMETER SearchScope
No type information available for this column.
.PARAMETER BindDN
No type information available for this column.
.PARAMETER BindPwd
No type information available for this column.
.PARAMETER GrpSearchDN
No type information available for this column.
.PARAMETER UseGroupMatch
No type information available for this column.
.PARAMETER DisplayNameOn
No type information available for this column.
.PARAMETER DisplayNameAttr
No type information available for this column.
.PARAMETER IsLdaps
No type information available for this column.
.PARAMETER Allowapi
No type information available for this column.
.PARAMETER NestedGroups
No type information available for this column.
.PARAMETER NestedDepth
No type information available for this column.
.PARAMETER TlsVerify
No type information available for this column.
.PARAMETER TlsCaCert
No type information available for this column.
.PARAMETER Ids
The objects to apply these values to. An empty or absent list matches nothing and edits nothing.
.OUTPUTS

JoinLdapRequest<PSCustomObject>
#>

function Initialize-FogJoinLdapRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Address},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Port},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SearchDN},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${UserNamAttr},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GrpNamAttr},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GrpMemberAttr},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SearchScope},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BindDN},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BindPwd},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GrpSearchDN},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${UseGroupMatch},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayNameOn},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayNameAttr},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IsLdaps},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Allowapi},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NestedGroups},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NestedDepth},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TlsVerify},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TlsCaCert},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${Ids}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogJoinLdapRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $Address) {
            throw "invalid value for 'Address', 'Address' cannot be null."
        }

        if ($null -eq $Port) {
            throw "invalid value for 'Port', 'Port' cannot be null."
        }

        if ($null -eq $SearchDN) {
            throw "invalid value for 'SearchDN', 'SearchDN' cannot be null."
        }

        if ($null -eq $SearchScope) {
            throw "invalid value for 'SearchScope', 'SearchScope' cannot be null."
        }

        if ($null -eq $UseGroupMatch) {
            throw "invalid value for 'UseGroupMatch', 'UseGroupMatch' cannot be null."
        }

        if ($null -eq $Ids) {
            throw "invalid value for 'Ids', 'Ids' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'description' = ${Description}
            'address' = ${Address}
            'port' = ${Port}
            'searchDN' = ${SearchDN}
            'userNamAttr' = ${UserNamAttr}
            'grpNamAttr' = ${GrpNamAttr}
            'grpMemberAttr' = ${GrpMemberAttr}
            'searchScope' = ${SearchScope}
            'bindDN' = ${BindDN}
            'bindPwd' = ${BindPwd}
            'grpSearchDN' = ${GrpSearchDN}
            'useGroupMatch' = ${UseGroupMatch}
            'displayNameOn' = ${DisplayNameOn}
            'displayNameAttr' = ${DisplayNameAttr}
            'isLdaps' = ${IsLdaps}
            'allowapi' = ${Allowapi}
            'nestedGroups' = ${NestedGroups}
            'nestedDepth' = ${NestedDepth}
            'tlsVerify' = ${TlsVerify}
            'tlsCaCert' = ${TlsCaCert}
            'ids' = ${Ids}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JoinLdapRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to JoinLdapRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JoinLdapRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToJoinLdapRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogJoinLdapRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogJoinLdapRequest
        $AllProperties = ('id', 'name', 'description', 'address', 'port', 'searchDN', 'userNamAttr', 'grpNamAttr', 'grpMemberAttr', 'searchScope', 'bindDN', 'bindPwd', 'grpSearchDN', 'useGroupMatch', 'displayNameOn', 'displayNameAttr', 'isLdaps', 'allowapi', 'nestedGroups', 'nestedDepth', 'tlsVerify', 'tlsCaCert', 'ids')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'address'))) {
            throw "Error! JSON cannot be serialized due to the required property 'address' missing."
        } else {
            $Address = $JsonParameters.PSobject.Properties['address'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'port'))) {
            throw "Error! JSON cannot be serialized due to the required property 'port' missing."
        } else {
            $Port = $JsonParameters.PSobject.Properties['port'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'searchDN'))) {
            throw "Error! JSON cannot be serialized due to the required property 'searchDN' missing."
        } else {
            $SearchDN = $JsonParameters.PSobject.Properties['searchDN'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'searchScope'))) {
            throw "Error! JSON cannot be serialized due to the required property 'searchScope' missing."
        } else {
            $SearchScope = $JsonParameters.PSobject.Properties['searchScope'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'useGroupMatch'))) {
            throw "Error! JSON cannot be serialized due to the required property 'useGroupMatch' missing."
        } else {
            $UseGroupMatch = $JsonParameters.PSobject.Properties['useGroupMatch'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ids'))) {
            throw "Error! JSON cannot be serialized due to the required property 'ids' missing."
        } else {
            $Ids = $JsonParameters.PSobject.Properties['ids'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'description'))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties['description'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'userNamAttr'))) { #optional property not found
            $UserNamAttr = $null
        } else {
            $UserNamAttr = $JsonParameters.PSobject.Properties['userNamAttr'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'grpNamAttr'))) { #optional property not found
            $GrpNamAttr = $null
        } else {
            $GrpNamAttr = $JsonParameters.PSobject.Properties['grpNamAttr'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'grpMemberAttr'))) { #optional property not found
            $GrpMemberAttr = $null
        } else {
            $GrpMemberAttr = $JsonParameters.PSobject.Properties['grpMemberAttr'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'bindDN'))) { #optional property not found
            $BindDN = $null
        } else {
            $BindDN = $JsonParameters.PSobject.Properties['bindDN'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'bindPwd'))) { #optional property not found
            $BindPwd = $null
        } else {
            $BindPwd = $JsonParameters.PSobject.Properties['bindPwd'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'grpSearchDN'))) { #optional property not found
            $GrpSearchDN = $null
        } else {
            $GrpSearchDN = $JsonParameters.PSobject.Properties['grpSearchDN'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'displayNameOn'))) { #optional property not found
            $DisplayNameOn = $null
        } else {
            $DisplayNameOn = $JsonParameters.PSobject.Properties['displayNameOn'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'displayNameAttr'))) { #optional property not found
            $DisplayNameAttr = $null
        } else {
            $DisplayNameAttr = $JsonParameters.PSobject.Properties['displayNameAttr'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'isLdaps'))) { #optional property not found
            $IsLdaps = $null
        } else {
            $IsLdaps = $JsonParameters.PSobject.Properties['isLdaps'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'allowapi'))) { #optional property not found
            $Allowapi = $null
        } else {
            $Allowapi = $JsonParameters.PSobject.Properties['allowapi'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'nestedGroups'))) { #optional property not found
            $NestedGroups = $null
        } else {
            $NestedGroups = $JsonParameters.PSobject.Properties['nestedGroups'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'nestedDepth'))) { #optional property not found
            $NestedDepth = $null
        } else {
            $NestedDepth = $JsonParameters.PSobject.Properties['nestedDepth'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'tlsVerify'))) { #optional property not found
            $TlsVerify = $null
        } else {
            $TlsVerify = $JsonParameters.PSobject.Properties['tlsVerify'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'tlsCaCert'))) { #optional property not found
            $TlsCaCert = $null
        } else {
            $TlsCaCert = $JsonParameters.PSobject.Properties['tlsCaCert'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'description' = ${Description}
            'address' = ${Address}
            'port' = ${Port}
            'searchDN' = ${SearchDN}
            'userNamAttr' = ${UserNamAttr}
            'grpNamAttr' = ${GrpNamAttr}
            'grpMemberAttr' = ${GrpMemberAttr}
            'searchScope' = ${SearchScope}
            'bindDN' = ${BindDN}
            'bindPwd' = ${BindPwd}
            'grpSearchDN' = ${GrpSearchDN}
            'useGroupMatch' = ${UseGroupMatch}
            'displayNameOn' = ${DisplayNameOn}
            'displayNameAttr' = ${DisplayNameAttr}
            'isLdaps' = ${IsLdaps}
            'allowapi' = ${Allowapi}
            'nestedGroups' = ${NestedGroups}
            'nestedDepth' = ${NestedDepth}
            'tlsVerify' = ${TlsVerify}
            'tlsCaCert' = ${TlsCaCert}
            'ids' = ${Ids}
        }

        return $PSO
    }

}

