#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No type information available for this column.
.PARAMETER ServerID
No type information available for this column.
.PARAMETER Name
No type information available for this column.
.PARAMETER Roles
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Usergroups
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Ldapserver
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Ids
The objects to apply these values to. An empty or absent list matches nothing and edits nothing.
.OUTPUTS

JoinLdapgroupRequest<PSCustomObject>
#>

function Initialize-FogJoinLdapgroupRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ServerID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Roles},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Usergroups},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Ldapserver},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${Ids}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogJoinLdapgroupRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ServerID) {
            throw "invalid value for 'ServerID', 'ServerID' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $Ids) {
            throw "invalid value for 'Ids', 'Ids' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'serverID' = ${ServerID}
            'name' = ${Name}
            'roles' = ${Roles}
            'usergroups' = ${Usergroups}
            'ldapserver' = ${Ldapserver}
            'ids' = ${Ids}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JoinLdapgroupRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to JoinLdapgroupRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JoinLdapgroupRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToJoinLdapgroupRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogJoinLdapgroupRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogJoinLdapgroupRequest
        $AllProperties = ('id', 'serverID', 'name', 'roles', 'usergroups', 'ldapserver', 'ids')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'serverID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'serverID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'serverID' missing."
        } else {
            $ServerID = $JsonParameters.PSobject.Properties['serverID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ids'))) {
            throw "Error! JSON cannot be serialized due to the required property 'ids' missing."
        } else {
            $Ids = $JsonParameters.PSobject.Properties['ids'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'roles'))) { #optional property not found
            $Roles = $null
        } else {
            $Roles = $JsonParameters.PSobject.Properties['roles'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'usergroups'))) { #optional property not found
            $Usergroups = $null
        } else {
            $Usergroups = $JsonParameters.PSobject.Properties['usergroups'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ldapserver'))) { #optional property not found
            $Ldapserver = $null
        } else {
            $Ldapserver = $JsonParameters.PSobject.Properties['ldapserver'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'serverID' = ${ServerID}
            'name' = ${Name}
            'roles' = ${Roles}
            'usergroups' = ${Usergroups}
            'ldapserver' = ${Ldapserver}
            'ids' = ${Ids}
        }

        return $PSO
    }

}

