#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER HostID
No description available.
.PARAMETER PrinterID
No description available.
.PARAMETER IsDefault
No description available.
.PARAMETER Anon1
No description available.
.PARAMETER Anon2
No description available.
.PARAMETER Anon3
No description available.
.PARAMETER Anon4
No description available.
.PARAMETER Anon5
No description available.
.PARAMETER Ids
The objects to apply these values to. An empty or absent list matches nothing and edits nothing.
.OUTPUTS

JoinPrinterassociationRequest<PSCustomObject>
#>

function Initialize-FogJoinPrinterassociationRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${HostID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${PrinterID},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IsDefault},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Anon1},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Anon2},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Anon3},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Anon4},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Anon5},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${Ids}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogJoinPrinterassociationRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $HostID) {
            throw "invalid value for 'HostID', 'HostID' cannot be null."
        }

        if ($null -eq $PrinterID) {
            throw "invalid value for 'PrinterID', 'PrinterID' cannot be null."
        }

        if (!$IsDefault -and $IsDefault.length -gt 2) {
            throw "invalid value for 'IsDefault', the character length must be smaller than or equal to 2."
        }

        if (!$Anon1 -and $Anon1.length -gt 2) {
            throw "invalid value for 'Anon1', the character length must be smaller than or equal to 2."
        }

        if (!$Anon2 -and $Anon2.length -gt 2) {
            throw "invalid value for 'Anon2', the character length must be smaller than or equal to 2."
        }

        if (!$Anon3 -and $Anon3.length -gt 2) {
            throw "invalid value for 'Anon3', the character length must be smaller than or equal to 2."
        }

        if (!$Anon4 -and $Anon4.length -gt 2) {
            throw "invalid value for 'Anon4', the character length must be smaller than or equal to 2."
        }

        if (!$Anon5 -and $Anon5.length -gt 2) {
            throw "invalid value for 'Anon5', the character length must be smaller than or equal to 2."
        }

        if ($null -eq $Ids) {
            throw "invalid value for 'Ids', 'Ids' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'hostID' = ${HostID}
            'printerID' = ${PrinterID}
            'isDefault' = ${IsDefault}
            'anon1' = ${Anon1}
            'anon2' = ${Anon2}
            'anon3' = ${Anon3}
            'anon4' = ${Anon4}
            'anon5' = ${Anon5}
            'ids' = ${Ids}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JoinPrinterassociationRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to JoinPrinterassociationRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JoinPrinterassociationRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToJoinPrinterassociationRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogJoinPrinterassociationRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogJoinPrinterassociationRequest
        $AllProperties = ('id', 'hostID', 'printerID', 'isDefault', 'anon1', 'anon2', 'anon3', 'anon4', 'anon5', 'ids')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'hostID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'hostID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'hostID' missing."
        } else {
            $HostID = $JsonParameters.PSobject.Properties['hostID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'printerID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'printerID' missing."
        } else {
            $PrinterID = $JsonParameters.PSobject.Properties['printerID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ids'))) {
            throw "Error! JSON cannot be serialized due to the required property 'ids' missing."
        } else {
            $Ids = $JsonParameters.PSobject.Properties['ids'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'isDefault'))) { #optional property not found
            $IsDefault = $null
        } else {
            $IsDefault = $JsonParameters.PSobject.Properties['isDefault'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'anon1'))) { #optional property not found
            $Anon1 = $null
        } else {
            $Anon1 = $JsonParameters.PSobject.Properties['anon1'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'anon2'))) { #optional property not found
            $Anon2 = $null
        } else {
            $Anon2 = $JsonParameters.PSobject.Properties['anon2'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'anon3'))) { #optional property not found
            $Anon3 = $null
        } else {
            $Anon3 = $JsonParameters.PSobject.Properties['anon3'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'anon4'))) { #optional property not found
            $Anon4 = $null
        } else {
            $Anon4 = $JsonParameters.PSobject.Properties['anon4'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'anon5'))) { #optional property not found
            $Anon5 = $null
        } else {
            $Anon5 = $JsonParameters.PSobject.Properties['anon5'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'hostID' = ${HostID}
            'printerID' = ${PrinterID}
            'isDefault' = ${IsDefault}
            'anon1' = ${Anon1}
            'anon2' = ${Anon2}
            'anon3' = ${Anon3}
            'anon4' = ${Anon4}
            'anon5' = ${Anon5}
            'ids' = ${Ids}
        }

        return $PSO
    }

}

