#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER SnapinID
No description available.
.PARAMETER StoragegroupID
No description available.
.PARAMETER Primary
No description available.
.PARAMETER Ids
The objects to apply these values to. An empty or absent list matches nothing and edits nothing.
.OUTPUTS

JoinSnapingroupassociationRequest<PSCustomObject>
#>

function Initialize-FogJoinSnapingroupassociationRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${SnapinID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${StoragegroupID},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${Primary} = "0",
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${Ids}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogJoinSnapingroupassociationRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $SnapinID) {
            throw "invalid value for 'SnapinID', 'SnapinID' cannot be null."
        }

        if ($null -eq $StoragegroupID) {
            throw "invalid value for 'StoragegroupID', 'StoragegroupID' cannot be null."
        }

        if ($null -eq $Ids) {
            throw "invalid value for 'Ids', 'Ids' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'snapinID' = ${SnapinID}
            'storagegroupID' = ${StoragegroupID}
            'primary' = ${Primary}
            'ids' = ${Ids}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JoinSnapingroupassociationRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to JoinSnapingroupassociationRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JoinSnapingroupassociationRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToJoinSnapingroupassociationRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogJoinSnapingroupassociationRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogJoinSnapingroupassociationRequest
        $AllProperties = ('id', 'snapinID', 'storagegroupID', 'primary', 'ids')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'snapinID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'snapinID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'snapinID' missing."
        } else {
            $SnapinID = $JsonParameters.PSobject.Properties['snapinID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'storagegroupID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'storagegroupID' missing."
        } else {
            $StoragegroupID = $JsonParameters.PSobject.Properties['storagegroupID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ids'))) {
            throw "Error! JSON cannot be serialized due to the required property 'ids' missing."
        } else {
            $Ids = $JsonParameters.PSobject.Properties['ids'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'primary'))) { #optional property not found
            $Primary = $null
        } else {
            $Primary = $JsonParameters.PSobject.Properties['primary'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'snapinID' = ${SnapinID}
            'storagegroupID' = ${StoragegroupID}
            'primary' = ${Primary}
            'ids' = ${Ids}
        }

        return $PSO
    }

}

