#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No type information available for this column.
.PARAMETER Name
No type information available for this column.
.PARAMETER UserID
No type information available for this column.
.PARAMETER TargetType
No type information available for this column.
.PARAMETER TargetID
No type information available for this column.
.PARAMETER Ids
The objects to apply these values to. An empty or absent list matches nothing and edits nothing.
.OUTPUTS

JoinLdapusergrantRequest<PSCustomObject>
#>

function Initialize-FogJoinLdapusergrantRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${UserID},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TargetType},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TargetID},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${Ids}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogJoinLdapusergrantRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $UserID) {
            throw "invalid value for 'UserID', 'UserID' cannot be null."
        }

        if ($null -eq $TargetType) {
            throw "invalid value for 'TargetType', 'TargetType' cannot be null."
        }

        if ($null -eq $TargetID) {
            throw "invalid value for 'TargetID', 'TargetID' cannot be null."
        }

        if ($null -eq $Ids) {
            throw "invalid value for 'Ids', 'Ids' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'userID' = ${UserID}
            'targetType' = ${TargetType}
            'targetID' = ${TargetID}
            'ids' = ${Ids}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JoinLdapusergrantRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to JoinLdapusergrantRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JoinLdapusergrantRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToJoinLdapusergrantRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogJoinLdapusergrantRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogJoinLdapusergrantRequest
        $AllProperties = ('id', 'name', 'userID', 'targetType', 'targetID', 'ids')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'userID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'userID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'userID' missing."
        } else {
            $UserID = $JsonParameters.PSobject.Properties['userID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'targetType'))) {
            throw "Error! JSON cannot be serialized due to the required property 'targetType' missing."
        } else {
            $TargetType = $JsonParameters.PSobject.Properties['targetType'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'targetID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'targetID' missing."
        } else {
            $TargetID = $JsonParameters.PSobject.Properties['targetID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ids'))) {
            throw "Error! JSON cannot be serialized due to the required property 'ids' missing."
        } else {
            $Ids = $JsonParameters.PSobject.Properties['ids'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'userID' = ${UserID}
            'targetType' = ${TargetType}
            'targetID' = ${TargetID}
            'ids' = ${Ids}
        }

        return $PSO
    }

}

