#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Product
No description available.
.PARAMETER Manufacturer
No description available.
.PARAMETER Mac
No description available.
.PARAMETER Success
No description available.
.PARAMETER Failure
No description available.
.PARAMETER File
No description available.
.PARAMETER Version
No description available.
.PARAMETER Ids
The objects to apply these values to. An empty or absent list matches nothing and edits nothing.
.OUTPUTS

JoinIpxeRequest<PSCustomObject>
#>

function Initialize-FogJoinIpxeRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Product},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Manufacturer},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Mac},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Success},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Failure},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${File},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Version},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${Ids}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogJoinIpxeRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Mac -and $Mac.length -gt 17) {
            throw "invalid value for 'Mac', the character length must be smaller than or equal to 17."
        }

        if (!$Success -and $Success.length -gt 2) {
            throw "invalid value for 'Success', the character length must be smaller than or equal to 2."
        }

        if (!$Failure -and $Failure.length -gt 2) {
            throw "invalid value for 'Failure', the character length must be smaller than or equal to 2."
        }

        if ($null -eq $Ids) {
            throw "invalid value for 'Ids', 'Ids' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'product' = ${Product}
            'manufacturer' = ${Manufacturer}
            'mac' = ${Mac}
            'success' = ${Success}
            'failure' = ${Failure}
            'file' = ${File}
            'version' = ${Version}
            'ids' = ${Ids}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JoinIpxeRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to JoinIpxeRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JoinIpxeRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToJoinIpxeRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogJoinIpxeRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogJoinIpxeRequest
        $AllProperties = ('id', 'product', 'manufacturer', 'mac', 'success', 'failure', 'file', 'version', 'ids')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'ids' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ids'))) {
            throw "Error! JSON cannot be serialized due to the required property 'ids' missing."
        } else {
            $Ids = $JsonParameters.PSobject.Properties['ids'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'product'))) { #optional property not found
            $Product = $null
        } else {
            $Product = $JsonParameters.PSobject.Properties['product'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'manufacturer'))) { #optional property not found
            $Manufacturer = $null
        } else {
            $Manufacturer = $JsonParameters.PSobject.Properties['manufacturer'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'mac'))) { #optional property not found
            $Mac = $null
        } else {
            $Mac = $JsonParameters.PSobject.Properties['mac'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'success'))) { #optional property not found
            $Success = $null
        } else {
            $Success = $JsonParameters.PSobject.Properties['success'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'failure'))) { #optional property not found
            $Failure = $null
        } else {
            $Failure = $JsonParameters.PSobject.Properties['failure'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'file'))) { #optional property not found
            $File = $null
        } else {
            $File = $JsonParameters.PSobject.Properties['file'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'version'))) { #optional property not found
            $Version = $null
        } else {
            $Version = $JsonParameters.PSobject.Properties['version'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'product' = ${Product}
            'manufacturer' = ${Manufacturer}
            'mac' = ${Mac}
            'success' = ${Success}
            'failure' = ${Failure}
            'file' = ${File}
            'version' = ${Version}
            'ids' = ${Ids}
        }

        return $PSO
    }

}

