#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER HostID
No description available.
.PARAMETER Mac
No description available.
.PARAMETER Description
No description available.
.PARAMETER Pending
No description available.
.PARAMETER Primary
No description available.
.PARAMETER ClientIgnore
No description available.
.PARAMETER ImageIgnore
No description available.
.PARAMETER VarHost
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Ids
The objects to apply these values to. An empty or absent list matches nothing and edits nothing.
.OUTPUTS

JoinMacaddressassociationRequest<PSCustomObject>
#>

function Initialize-FogJoinMacaddressassociationRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${HostID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Mac},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${Pending} = "0",
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${Primary} = "0",
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${ClientIgnore} = "0",
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${ImageIgnore} = "0",
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VarHost},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${Ids}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogJoinMacaddressassociationRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $HostID) {
            throw "invalid value for 'HostID', 'HostID' cannot be null."
        }

        if ($null -eq $Mac) {
            throw "invalid value for 'Mac', 'Mac' cannot be null."
        }

        if ($Mac.length -gt 59) {
            throw "invalid value for 'Mac', the character length must be smaller than or equal to 59."
        }

        if ($null -eq $Ids) {
            throw "invalid value for 'Ids', 'Ids' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'hostID' = ${HostID}
            'mac' = ${Mac}
            'description' = ${Description}
            'pending' = ${Pending}
            'primary' = ${Primary}
            'clientIgnore' = ${ClientIgnore}
            'imageIgnore' = ${ImageIgnore}
            'host' = ${VarHost}
            'ids' = ${Ids}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JoinMacaddressassociationRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to JoinMacaddressassociationRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JoinMacaddressassociationRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToJoinMacaddressassociationRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogJoinMacaddressassociationRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogJoinMacaddressassociationRequest
        $AllProperties = ('id', 'hostID', 'mac', 'description', 'pending', 'primary', 'clientIgnore', 'imageIgnore', 'host', 'ids')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'hostID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'hostID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'hostID' missing."
        } else {
            $HostID = $JsonParameters.PSobject.Properties['hostID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'mac'))) {
            throw "Error! JSON cannot be serialized due to the required property 'mac' missing."
        } else {
            $Mac = $JsonParameters.PSobject.Properties['mac'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ids'))) {
            throw "Error! JSON cannot be serialized due to the required property 'ids' missing."
        } else {
            $Ids = $JsonParameters.PSobject.Properties['ids'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'description'))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties['description'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'pending'))) { #optional property not found
            $Pending = $null
        } else {
            $Pending = $JsonParameters.PSobject.Properties['pending'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'primary'))) { #optional property not found
            $Primary = $null
        } else {
            $Primary = $JsonParameters.PSobject.Properties['primary'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'clientIgnore'))) { #optional property not found
            $ClientIgnore = $null
        } else {
            $ClientIgnore = $JsonParameters.PSobject.Properties['clientIgnore'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'imageIgnore'))) { #optional property not found
            $ImageIgnore = $null
        } else {
            $ImageIgnore = $JsonParameters.PSobject.Properties['imageIgnore'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'host'))) { #optional property not found
            $VarHost = $null
        } else {
            $VarHost = $JsonParameters.PSobject.Properties['host'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'hostID' = ${HostID}
            'mac' = ${Mac}
            'description' = ${Description}
            'pending' = ${Pending}
            'primary' = ${Primary}
            'clientIgnore' = ${ClientIgnore}
            'imageIgnore' = ${ImageIgnore}
            'host' = ${VarHost}
            'ids' = ${Ids}
        }

        return $PSO
    }

}

