#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Names
Names to resolve. Each is created if no object already has it.
.OUTPUTS

JoinByNameGroupRequest<PSCustomObject>
#>

function Initialize-FogJoinByNameGroupRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Names}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogJoinByNameGroupRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Names) {
            throw "invalid value for 'Names', 'Names' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'names' = ${Names}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to JoinByNameGroupRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to JoinByNameGroupRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

JoinByNameGroupRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToJoinByNameGroupRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogJoinByNameGroupRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogJoinByNameGroupRequest
        $AllProperties = ('names')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'names' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'names'))) {
            throw "Error! JSON cannot be serialized due to the required property 'names' missing."
        } else {
            $Names = $JsonParameters.PSobject.Properties['names'].value
        }

        $PSO = [PSCustomObject]@{
            'names' = ${Names}
        }

        return $PSO
    }

}

