#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No type information available for this column.
.PARAMETER Name
No type information available for this column.
.PARAMETER LdapgroupID
No type information available for this column.
.PARAMETER UsergroupID
No type information available for this column.
.OUTPUTS

Ldapgroupusergroupassociation<PSCustomObject>
#>

function Initialize-FogLdapgroupusergroupassociation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LdapgroupID},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${UsergroupID}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogLdapgroupusergroupassociation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $LdapgroupID) {
            throw "invalid value for 'LdapgroupID', 'LdapgroupID' cannot be null."
        }

        if ($null -eq $UsergroupID) {
            throw "invalid value for 'UsergroupID', 'UsergroupID' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'ldapgroupID' = ${LdapgroupID}
            'usergroupID' = ${UsergroupID}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Ldapgroupusergroupassociation<PSCustomObject>

.DESCRIPTION

Convert from JSON to Ldapgroupusergroupassociation<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Ldapgroupusergroupassociation<PSCustomObject>
#>
function ConvertFrom-FogJsonToLdapgroupusergroupassociation {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogLdapgroupusergroupassociation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FogLdapgroupusergroupassociationAdditionalProperties = @{}

        # check if Json contains properties not defined in FogLdapgroupusergroupassociation
        $AllProperties = ('id', 'name', 'ldapgroupID', 'usergroupID')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FogLdapgroupusergroupassociationAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'ldapgroupID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ldapgroupID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'ldapgroupID' missing."
        } else {
            $LdapgroupID = $JsonParameters.PSobject.Properties['ldapgroupID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'usergroupID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'usergroupID' missing."
        } else {
            $UsergroupID = $JsonParameters.PSobject.Properties['usergroupID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'ldapgroupID' = ${LdapgroupID}
            'usergroupID' = ${UsergroupID}
            'AdditionalProperties' = $FogLdapgroupusergroupassociationAdditionalProperties
        }

        return $PSO
    }

}

