#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Responses may carry computed fields that are not columns and are not settable through the generic create/edit path: imagename, state.

.PARAMETER Id
No description available.
.PARAMETER Name
No description available.
.PARAMETER Port
No description available.
.PARAMETER Logpath
No description available.
.PARAMETER Image
No description available.
.PARAMETER Clients
No description available.
.PARAMETER Sessclients
No description available.
.PARAMETER Interface
No description available.
.PARAMETER Starttime
No description available.
.PARAMETER Percent
No description available.
.PARAMETER StateID
No description available.
.PARAMETER Completetime
No description available.
.PARAMETER IsDD
No description available.
.PARAMETER StoragegroupID
No description available.
.PARAMETER Shutdown
No description available.
.PARAMETER Maxwait
No description available.
.PARAMETER Senderpid
No description available.
.PARAMETER Sendernode
No description available.
.PARAMETER Senderstart
No description available.
.PARAMETER Anon5
No description available.
.PARAMETER Imagename
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER State
Computed field. Returned by the API but not a column, and not settable.
.OUTPUTS

Multicastsession<PSCustomObject>
#>

function Initialize-FogMulticastsession {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Port} = 0,
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Logpath},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Image},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Clients} = 0,
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Sessclients} = 0,
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Interface},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Starttime},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Percent} = 0,
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${StateID} = 0,
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Completetime},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${IsDD} = 0,
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${StoragegroupID},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${Shutdown} = "0",
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Maxwait} = 0,
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Senderpid} = 0,
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Sendernode} = 0,
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Senderstart},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Anon5},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Imagename},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${State}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogMulticastsession' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Name -and $Name.length -gt 250) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 250."
        }

        if (!$Interface -and $Interface.length -gt 250) {
            throw "invalid value for 'Interface', the character length must be smaller than or equal to 250."
        }

        if (!$Anon5 -and $Anon5.length -gt 250) {
            throw "invalid value for 'Anon5', the character length must be smaller than or equal to 250."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'port' = ${Port}
            'logpath' = ${Logpath}
            'image' = ${Image}
            'clients' = ${Clients}
            'sessclients' = ${Sessclients}
            'interface' = ${Interface}
            'starttime' = ${Starttime}
            'percent' = ${Percent}
            'stateID' = ${StateID}
            'completetime' = ${Completetime}
            'isDD' = ${IsDD}
            'storagegroupID' = ${StoragegroupID}
            'shutdown' = ${Shutdown}
            'maxwait' = ${Maxwait}
            'senderpid' = ${Senderpid}
            'sendernode' = ${Sendernode}
            'senderstart' = ${Senderstart}
            'anon5' = ${Anon5}
            'imagename' = ${Imagename}
            'state' = ${State}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Multicastsession<PSCustomObject>

.DESCRIPTION

Convert from JSON to Multicastsession<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Multicastsession<PSCustomObject>
#>
function ConvertFrom-FogJsonToMulticastsession {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogMulticastsession' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FogMulticastsessionAdditionalProperties = @{}

        # check if Json contains properties not defined in FogMulticastsession
        $AllProperties = ('id', 'name', 'port', 'logpath', 'image', 'clients', 'sessclients', 'interface', 'starttime', 'percent', 'stateID', 'completetime', 'isDD', 'storagegroupID', 'shutdown', 'maxwait', 'senderpid', 'sendernode', 'senderstart', 'anon5', 'imagename', 'state')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FogMulticastsessionAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'port'))) { #optional property not found
            $Port = $null
        } else {
            $Port = $JsonParameters.PSobject.Properties['port'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'logpath'))) { #optional property not found
            $Logpath = $null
        } else {
            $Logpath = $JsonParameters.PSobject.Properties['logpath'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'image'))) { #optional property not found
            $Image = $null
        } else {
            $Image = $JsonParameters.PSobject.Properties['image'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'clients'))) { #optional property not found
            $Clients = $null
        } else {
            $Clients = $JsonParameters.PSobject.Properties['clients'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'sessclients'))) { #optional property not found
            $Sessclients = $null
        } else {
            $Sessclients = $JsonParameters.PSobject.Properties['sessclients'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'interface'))) { #optional property not found
            $Interface = $null
        } else {
            $Interface = $JsonParameters.PSobject.Properties['interface'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'starttime'))) { #optional property not found
            $Starttime = $null
        } else {
            $Starttime = $JsonParameters.PSobject.Properties['starttime'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'percent'))) { #optional property not found
            $Percent = $null
        } else {
            $Percent = $JsonParameters.PSobject.Properties['percent'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'stateID'))) { #optional property not found
            $StateID = $null
        } else {
            $StateID = $JsonParameters.PSobject.Properties['stateID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'completetime'))) { #optional property not found
            $Completetime = $null
        } else {
            $Completetime = $JsonParameters.PSobject.Properties['completetime'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'isDD'))) { #optional property not found
            $IsDD = $null
        } else {
            $IsDD = $JsonParameters.PSobject.Properties['isDD'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'storagegroupID'))) { #optional property not found
            $StoragegroupID = $null
        } else {
            $StoragegroupID = $JsonParameters.PSobject.Properties['storagegroupID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'shutdown'))) { #optional property not found
            $Shutdown = $null
        } else {
            $Shutdown = $JsonParameters.PSobject.Properties['shutdown'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'maxwait'))) { #optional property not found
            $Maxwait = $null
        } else {
            $Maxwait = $JsonParameters.PSobject.Properties['maxwait'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'senderpid'))) { #optional property not found
            $Senderpid = $null
        } else {
            $Senderpid = $JsonParameters.PSobject.Properties['senderpid'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'sendernode'))) { #optional property not found
            $Sendernode = $null
        } else {
            $Sendernode = $JsonParameters.PSobject.Properties['sendernode'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'senderstart'))) { #optional property not found
            $Senderstart = $null
        } else {
            $Senderstart = $JsonParameters.PSobject.Properties['senderstart'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'anon5'))) { #optional property not found
            $Anon5 = $null
        } else {
            $Anon5 = $JsonParameters.PSobject.Properties['anon5'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'imagename'))) { #optional property not found
            $Imagename = $null
        } else {
            $Imagename = $JsonParameters.PSobject.Properties['imagename'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'state'))) { #optional property not found
            $State = $null
        } else {
            $State = $JsonParameters.PSobject.Properties['state'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'port' = ${Port}
            'logpath' = ${Logpath}
            'image' = ${Image}
            'clients' = ${Clients}
            'sessclients' = ${Sessclients}
            'interface' = ${Interface}
            'starttime' = ${Starttime}
            'percent' = ${Percent}
            'stateID' = ${StateID}
            'completetime' = ${Completetime}
            'isDD' = ${IsDD}
            'storagegroupID' = ${StoragegroupID}
            'shutdown' = ${Shutdown}
            'maxwait' = ${Maxwait}
            'senderpid' = ${Senderpid}
            'sendernode' = ${Sendernode}
            'senderstart' = ${Senderstart}
            'anon5' = ${Anon5}
            'imagename' = ${Imagename}
            'state' = ${State}
            'AdditionalProperties' = $FogMulticastsessionAdditionalProperties
        }

        return $PSO
    }

}

