#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER MsID
No description available.
.PARAMETER TaskID
No description available.
.OUTPUTS

Multicastsessionassociation<PSCustomObject>
#>

function Initialize-FogMulticastsessionassociation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${MsID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${TaskID}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogMulticastsessionassociation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $MsID) {
            throw "invalid value for 'MsID', 'MsID' cannot be null."
        }

        if ($null -eq $TaskID) {
            throw "invalid value for 'TaskID', 'TaskID' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'msID' = ${MsID}
            'taskID' = ${TaskID}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Multicastsessionassociation<PSCustomObject>

.DESCRIPTION

Convert from JSON to Multicastsessionassociation<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Multicastsessionassociation<PSCustomObject>
#>
function ConvertFrom-FogJsonToMulticastsessionassociation {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogMulticastsessionassociation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FogMulticastsessionassociationAdditionalProperties = @{}

        # check if Json contains properties not defined in FogMulticastsessionassociation
        $AllProperties = ('id', 'msID', 'taskID')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FogMulticastsessionassociationAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'msID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'msID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'msID' missing."
        } else {
            $MsID = $JsonParameters.PSobject.Properties['msID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'taskID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'taskID' missing."
        } else {
            $TaskID = $JsonParameters.PSobject.Properties['taskID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'msID' = ${MsID}
            'taskID' = ${TaskID}
            'AdditionalProperties' = $FogMulticastsessionassociationAdditionalProperties
        }

        return $PSO
    }

}

