#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Responses may carry computed fields that are not columns and are not settable through the generic create/edit path: users, hosts, groups, usergroups, grantroles, grantusergroups, catchall.

.PARAMETER Id
No description available.
.PARAMETER Name
No description available.
.PARAMETER Description
No description available.
.PARAMETER Users
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Hosts
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Groups
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Usergroups
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Grantroles
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Grantusergroups
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Catchall
Computed field. Returned by the API but not a column, and not settable.
.OUTPUTS

Site<PSCustomObject>
#>

function Initialize-FogSite {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Users},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Hosts},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Groups},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Usergroups},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Grantroles},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Grantusergroups},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Catchall}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogSite' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($Name.length -gt 255) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 255."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'description' = ${Description}
            'users' = ${Users}
            'hosts' = ${Hosts}
            'groups' = ${Groups}
            'usergroups' = ${Usergroups}
            'grantroles' = ${Grantroles}
            'grantusergroups' = ${Grantusergroups}
            'catchall' = ${Catchall}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Site<PSCustomObject>

.DESCRIPTION

Convert from JSON to Site<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Site<PSCustomObject>
#>
function ConvertFrom-FogJsonToSite {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogSite' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FogSiteAdditionalProperties = @{}

        # check if Json contains properties not defined in FogSite
        $AllProperties = ('id', 'name', 'description', 'users', 'hosts', 'groups', 'usergroups', 'grantroles', 'grantusergroups', 'catchall')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FogSiteAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'description'))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties['description'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'users'))) { #optional property not found
            $Users = $null
        } else {
            $Users = $JsonParameters.PSobject.Properties['users'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'hosts'))) { #optional property not found
            $Hosts = $null
        } else {
            $Hosts = $JsonParameters.PSobject.Properties['hosts'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'groups'))) { #optional property not found
            $Groups = $null
        } else {
            $Groups = $JsonParameters.PSobject.Properties['groups'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'usergroups'))) { #optional property not found
            $Usergroups = $null
        } else {
            $Usergroups = $JsonParameters.PSobject.Properties['usergroups'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'grantroles'))) { #optional property not found
            $Grantroles = $null
        } else {
            $Grantroles = $JsonParameters.PSobject.Properties['grantroles'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'grantusergroups'))) { #optional property not found
            $Grantusergroups = $null
        } else {
            $Grantusergroups = $JsonParameters.PSobject.Properties['grantusergroups'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'catchall'))) { #optional property not found
            $Catchall = $null
        } else {
            $Catchall = $JsonParameters.PSobject.Properties['catchall'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'description' = ${Description}
            'users' = ${Users}
            'hosts' = ${Hosts}
            'groups' = ${Groups}
            'usergroups' = ${Usergroups}
            'grantroles' = ${Grantroles}
            'grantusergroups' = ${Grantusergroups}
            'catchall' = ${Catchall}
            'AdditionalProperties' = $FogSiteAdditionalProperties
        }

        return $PSO
    }

}

