#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Responses may carry computed fields that are not columns and are not settable through the generic create/edit path: host, state, snapintasks.

.PARAMETER Id
No description available.
.PARAMETER HostID
No description available.
.PARAMETER StateID
No description available.
.PARAMETER AbortOnFail
No description available.
.PARAMETER VarHost
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER State
Computed field. Returned by the API but not a column, and not settable.
.PARAMETER Snapintasks
Computed field. Returned by the API but not a column, and not settable.
.OUTPUTS

Snapinjob<PSCustomObject>
#>

function Initialize-FogSnapinjob {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${HostID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${StateID},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${AbortOnFail} = "0",
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VarHost},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${State},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Snapintasks}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogSnapinjob' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $HostID) {
            throw "invalid value for 'HostID', 'HostID' cannot be null."
        }

        if ($null -eq $StateID) {
            throw "invalid value for 'StateID', 'StateID' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'hostID' = ${HostID}
            'stateID' = ${StateID}
            'abortOnFail' = ${AbortOnFail}
            'host' = ${VarHost}
            'state' = ${State}
            'snapintasks' = ${Snapintasks}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Snapinjob<PSCustomObject>

.DESCRIPTION

Convert from JSON to Snapinjob<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Snapinjob<PSCustomObject>
#>
function ConvertFrom-FogJsonToSnapinjob {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogSnapinjob' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FogSnapinjobAdditionalProperties = @{}

        # check if Json contains properties not defined in FogSnapinjob
        $AllProperties = ('id', 'hostID', 'stateID', 'abortOnFail', 'host', 'state', 'snapintasks')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FogSnapinjobAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'hostID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'hostID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'hostID' missing."
        } else {
            $HostID = $JsonParameters.PSobject.Properties['hostID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'stateID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'stateID' missing."
        } else {
            $StateID = $JsonParameters.PSobject.Properties['stateID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'abortOnFail'))) { #optional property not found
            $AbortOnFail = $null
        } else {
            $AbortOnFail = $JsonParameters.PSobject.Properties['abortOnFail'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'host'))) { #optional property not found
            $VarHost = $null
        } else {
            $VarHost = $JsonParameters.PSobject.Properties['host'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'state'))) { #optional property not found
            $State = $null
        } else {
            $State = $JsonParameters.PSobject.Properties['state'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'snapintasks'))) { #optional property not found
            $Snapintasks = $null
        } else {
            $Snapintasks = $JsonParameters.PSobject.Properties['snapintasks'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'hostID' = ${HostID}
            'stateID' = ${StateID}
            'abortOnFail' = ${AbortOnFail}
            'host' = ${VarHost}
            'state' = ${State}
            'snapintasks' = ${Snapintasks}
            'AdditionalProperties' = $FogSnapinjobAdditionalProperties
        }

        return $PSO
    }

}

