#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Responses may carry computed fields that are not columns and are not settable through the generic create/edit path: snapin, state, snapinjob.

.PARAMETER Id
No description available.
.PARAMETER JobID
No description available.
.PARAMETER StateID
No description available.
.PARAMETER Checkin
No description available.
.PARAMETER Complete
No description available.
.PARAMETER SnapinID
No description available.
.PARAMETER Sequence
No description available.
.PARAMETER VarReturn
No description available.
.PARAMETER Details
No description available.
.OUTPUTS

Snapintask<PSCustomObject>
#>

function Initialize-FogSnapintask {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${JobID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${StateID} = 0,
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Checkin},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${Complete},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${SnapinID},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Sequence} = 0,
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${VarReturn} = 0,
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Details}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogSnapintask' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $JobID) {
            throw "invalid value for 'JobID', 'JobID' cannot be null."
        }

        if ($null -eq $SnapinID) {
            throw "invalid value for 'SnapinID', 'SnapinID' cannot be null."
        }

        if (!$Details -and $Details.length -gt 250) {
            throw "invalid value for 'Details', the character length must be smaller than or equal to 250."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'jobID' = ${JobID}
            'stateID' = ${StateID}
            'checkin' = ${Checkin}
            'complete' = ${Complete}
            'snapinID' = ${SnapinID}
            'sequence' = ${Sequence}
            'return' = ${VarReturn}
            'details' = ${Details}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Snapintask<PSCustomObject>

.DESCRIPTION

Convert from JSON to Snapintask<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Snapintask<PSCustomObject>
#>
function ConvertFrom-FogJsonToSnapintask {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogSnapintask' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogSnapintask
        $AllProperties = ('id', 'jobID', 'stateID', 'checkin', 'complete', 'snapinID', 'sequence', 'return', 'details')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'jobID' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'jobID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'jobID' missing."
        } else {
            $JobID = $JsonParameters.PSobject.Properties['jobID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'snapinID'))) {
            throw "Error! JSON cannot be serialized due to the required property 'snapinID' missing."
        } else {
            $SnapinID = $JsonParameters.PSobject.Properties['snapinID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'stateID'))) { #optional property not found
            $StateID = $null
        } else {
            $StateID = $JsonParameters.PSobject.Properties['stateID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'checkin'))) { #optional property not found
            $Checkin = $null
        } else {
            $Checkin = $JsonParameters.PSobject.Properties['checkin'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'complete'))) { #optional property not found
            $Complete = $null
        } else {
            $Complete = $JsonParameters.PSobject.Properties['complete'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'sequence'))) { #optional property not found
            $Sequence = $null
        } else {
            $Sequence = $JsonParameters.PSobject.Properties['sequence'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'return'))) { #optional property not found
            $VarReturn = $null
        } else {
            $VarReturn = $JsonParameters.PSobject.Properties['return'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'details'))) { #optional property not found
            $Details = $null
        } else {
            $Details = $JsonParameters.PSobject.Properties['details'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'jobID' = ${JobID}
            'stateID' = ${StateID}
            'checkin' = ${Checkin}
            'complete' = ${Complete}
            'snapinID' = ${SnapinID}
            'sequence' = ${Sequence}
            'return' = ${VarReturn}
            'details' = ${Details}
        }

        return $PSO
    }

}

