#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: issue an API token from the API tab and send it as `Authorization: Bearer <token>`, which needs nothing else. These are `fog_` prefixed, hashed at rest and shown once; a user may hold several, each revocable on its own. They are a separate credential from the per-user token that `fog-user-token` carries, which Bearer does not accept. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4020
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Name
No description available.
.PARAMETER Description
No description available.
.PARAMETER Icon
No description available.
.PARAMETER Kernel
No description available.
.PARAMETER KernelArgs
No description available.
.PARAMETER Type
No description available.
.PARAMETER IsAdvanced
No description available.
.PARAMETER Access
No description available.
.PARAMETER Initrd
No description available.
.OUTPUTS

Tasktype<PSCustomObject>
#>

function Initialize-FogTasktype {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Icon},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Kernel},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${KernelArgs},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("fog", "user")]
        [String]
        ${Type} = "user",
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("0", "1")]
        [String]
        ${IsAdvanced} = "0",
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("both", "host", "group")]
        [String]
        ${Access} = "both",
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Initrd}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogTasktype' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($Name.length -gt 30) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 30."
        }

        if ($null -eq $Icon) {
            throw "invalid value for 'Icon', 'Icon' cannot be null."
        }

        if ($Icon.length -gt 30) {
            throw "invalid value for 'Icon', the character length must be smaller than or equal to 30."
        }

        if (!$Kernel -and $Kernel.length -gt 100) {
            throw "invalid value for 'Kernel', the character length must be smaller than or equal to 100."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'description' = ${Description}
            'icon' = ${Icon}
            'kernel' = ${Kernel}
            'kernelArgs' = ${KernelArgs}
            'type' = ${Type}
            'isAdvanced' = ${IsAdvanced}
            'access' = ${Access}
            'initrd' = ${Initrd}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Tasktype<PSCustomObject>

.DESCRIPTION

Convert from JSON to Tasktype<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Tasktype<PSCustomObject>
#>
function ConvertFrom-FogJsonToTasktype {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogTasktype' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FogTasktypeAdditionalProperties = @{}

        # check if Json contains properties not defined in FogTasktype
        $AllProperties = ('id', 'name', 'description', 'icon', 'kernel', 'kernelArgs', 'type', 'isAdvanced', 'access', 'initrd')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FogTasktypeAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'icon'))) {
            throw "Error! JSON cannot be serialized due to the required property 'icon' missing."
        } else {
            $Icon = $JsonParameters.PSobject.Properties['icon'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'description'))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties['description'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'kernel'))) { #optional property not found
            $Kernel = $null
        } else {
            $Kernel = $JsonParameters.PSobject.Properties['kernel'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'kernelArgs'))) { #optional property not found
            $KernelArgs = $null
        } else {
            $KernelArgs = $JsonParameters.PSobject.Properties['kernelArgs'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'type'))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties['type'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'isAdvanced'))) { #optional property not found
            $IsAdvanced = $null
        } else {
            $IsAdvanced = $JsonParameters.PSobject.Properties['isAdvanced'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'access'))) { #optional property not found
            $Access = $null
        } else {
            $Access = $JsonParameters.PSobject.Properties['access'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'initrd'))) { #optional property not found
            $Initrd = $null
        } else {
            $Initrd = $JsonParameters.PSobject.Properties['initrd'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'name' = ${Name}
            'description' = ${Description}
            'icon' = ${Icon}
            'kernel' = ${Kernel}
            'kernelArgs' = ${KernelArgs}
            'type' = ${Type}
            'isAdvanced' = ${IsAdvanced}
            'access' = ${Access}
            'initrd' = ${Initrd}
            'AdditionalProperties' = $FogTasktypeAdditionalProperties
        }

        return $PSO
    }

}

