#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TaskTypeID
No description available.
.PARAMETER TaskName
No description available.
.PARAMETER Shutdown
No description available.
.PARAMETER Debug
No description available.
.PARAMETER DeploySnapins
No description available.
.PARAMETER Passreset
No description available.
.PARAMETER Sessionjoin
No description available.
.PARAMETER Wol
No description available.
.OUTPUTS

TaskFiledeletequeueRequest<PSCustomObject>
#>

function Initialize-FogTaskFiledeletequeueRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TaskTypeID},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TaskName},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Shutdown},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Debug},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DeploySnapins},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Passreset},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Sessionjoin},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Wol}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogTaskFiledeletequeueRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            'taskTypeID' = ${TaskTypeID}
            'taskName' = ${TaskName}
            'shutdown' = ${Shutdown}
            'debug' = ${Debug}
            'deploySnapins' = ${DeploySnapins}
            'passreset' = ${Passreset}
            'sessionjoin' = ${Sessionjoin}
            'wol' = ${Wol}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TaskFiledeletequeueRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to TaskFiledeletequeueRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TaskFiledeletequeueRequest<PSCustomObject>
#>
function ConvertFrom-FogJsonToTaskFiledeletequeueRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogTaskFiledeletequeueRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogTaskFiledeletequeueRequest
        $AllProperties = ('taskTypeID', 'taskName', 'shutdown', 'debug', 'deploySnapins', 'passreset', 'sessionjoin', 'wol')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'taskTypeID'))) { #optional property not found
            $TaskTypeID = $null
        } else {
            $TaskTypeID = $JsonParameters.PSobject.Properties['taskTypeID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'taskName'))) { #optional property not found
            $TaskName = $null
        } else {
            $TaskName = $JsonParameters.PSobject.Properties['taskName'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'shutdown'))) { #optional property not found
            $Shutdown = $null
        } else {
            $Shutdown = $JsonParameters.PSobject.Properties['shutdown'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'debug'))) { #optional property not found
            $Debug = $null
        } else {
            $Debug = $JsonParameters.PSobject.Properties['debug'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'deploySnapins'))) { #optional property not found
            $DeploySnapins = $null
        } else {
            $DeploySnapins = $JsonParameters.PSobject.Properties['deploySnapins'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'passreset'))) { #optional property not found
            $Passreset = $null
        } else {
            $Passreset = $JsonParameters.PSobject.Properties['passreset'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'sessionjoin'))) { #optional property not found
            $Sessionjoin = $null
        } else {
            $Sessionjoin = $JsonParameters.PSobject.Properties['sessionjoin'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'wol'))) { #optional property not found
            $Wol = $null
        } else {
            $Wol = $JsonParameters.PSobject.Properties['wol'].value
        }

        $PSO = [PSCustomObject]@{
            'taskTypeID' = ${TaskTypeID}
            'taskName' = ${TaskName}
            'shutdown' = ${Shutdown}
            'debug' = ${Debug}
            'deploySnapins' = ${DeploySnapins}
            'passreset' = ${Passreset}
            'sessionjoin' = ${Sessionjoin}
            'wol' = ${Wol}
        }

        return $PSO
    }

}

