#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER TaskID
No description available.
.PARAMETER StateID
No description available.
.PARAMETER Ip
No description available.
.PARAMETER Type
No description available.
.PARAMETER Text
No description available.
.PARAMETER HostID
No description available.
.PARAMETER HostName
No description available.
.PARAMETER TaskTypeName
No description available.
.PARAMETER ImageName
No description available.
.OUTPUTS

Tasklog<PSCustomObject>
#>

function Initialize-FogTasklog {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${TaskID},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${StateID},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Ip},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type} = "state",
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Text},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${HostID},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HostName},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TaskTypeName},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ImageName}
    )

    Process {
        'Creating PSCustomObject: FogApi => FogTasklog' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Ip -and $Ip.length -gt 15) {
            throw "invalid value for 'Ip', the character length must be smaller than or equal to 15."
        }

        if (!$Type -and $Type.length -gt 16) {
            throw "invalid value for 'Type', the character length must be smaller than or equal to 16."
        }

        if (!$HostName -and $HostName.length -gt 16) {
            throw "invalid value for 'HostName', the character length must be smaller than or equal to 16."
        }

        if (!$TaskTypeName -and $TaskTypeName.length -gt 30) {
            throw "invalid value for 'TaskTypeName', the character length must be smaller than or equal to 30."
        }

        if (!$ImageName -and $ImageName.length -gt 40) {
            throw "invalid value for 'ImageName', the character length must be smaller than or equal to 40."
        }


        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'taskID' = ${TaskID}
            'stateID' = ${StateID}
            'ip' = ${Ip}
            'type' = ${Type}
            'text' = ${Text}
            'hostID' = ${HostID}
            'hostName' = ${HostName}
            'taskTypeName' = ${TaskTypeName}
            'imageName' = ${ImageName}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Tasklog<PSCustomObject>

.DESCRIPTION

Convert from JSON to Tasklog<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Tasklog<PSCustomObject>
#>
function ConvertFrom-FogJsonToTasklog {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FogApi => FogTasklog' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FogTasklog
        $AllProperties = ('id', 'taskID', 'stateID', 'ip', 'type', 'text', 'hostID', 'hostName', 'taskTypeName', 'imageName')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'taskID'))) { #optional property not found
            $TaskID = $null
        } else {
            $TaskID = $JsonParameters.PSobject.Properties['taskID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'stateID'))) { #optional property not found
            $StateID = $null
        } else {
            $StateID = $JsonParameters.PSobject.Properties['stateID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'ip'))) { #optional property not found
            $Ip = $null
        } else {
            $Ip = $JsonParameters.PSobject.Properties['ip'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'type'))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties['type'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'text'))) { #optional property not found
            $Text = $null
        } else {
            $Text = $JsonParameters.PSobject.Properties['text'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'hostID'))) { #optional property not found
            $HostID = $null
        } else {
            $HostID = $JsonParameters.PSobject.Properties['hostID'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'hostName'))) { #optional property not found
            $HostName = $null
        } else {
            $HostName = $JsonParameters.PSobject.Properties['hostName'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'taskTypeName'))) { #optional property not found
            $TaskTypeName = $null
        } else {
            $TaskTypeName = $JsonParameters.PSobject.Properties['taskTypeName'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'imageName'))) { #optional property not found
            $ImageName = $null
        } else {
            $ImageName = $JsonParameters.PSobject.Properties['imageName'].value
        }

        $PSO = [PSCustomObject]@{
            'id' = ${Id}
            'taskID' = ${TaskID}
            'stateID' = ${StateID}
            'ip' = ${Ip}
            'type' = ${Type}
            'text' = ${Text}
            'hostID' = ${HostID}
            'hostName' = ${HostName}
            'taskTypeName' = ${TaskTypeName}
            'imageName' = ${ImageName}
        }

        return $PSO
    }

}

