#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogJoinRoleuserassociationRequest' {
    Context 'FogJoinRoleuserassociationRequest' {
        It 'Initialize-FogJoinRoleuserassociationRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-FogJoinRoleuserassociationRequest -Id "TEST_VALUE" -Name "TEST_VALUE" -RoleID "TEST_VALUE" -UserID "TEST_VALUE" -Ids "TEST_VALUE"
            #$NewObject | Should -BeOfType JoinRoleuserassociationRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
