#
# FOG Project API
# Generated from this server's own routing and model metadata, so it describes the classes and routes THIS server exposes, including any a plugin has added.  Enable under FOG Configuration > FOG Settings > API System. Preferred: send the per-user API token as `Authorization: Bearer <token>`, which needs nothing else. Otherwise the `fog-api-token` (server-wide) header is required, plus one caller identity -- either the `fog-user-token` header or HTTP basic auth. Basic auth does not replace the `fog-api-token` header.  Field names: every property is also addressable by its raw database column name, because the model layer flips $databaseFields into $databaseFieldsFlipped and accepts either spelling. Only the property name is documented here.
# Version: 1.6.0-beta.4013
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FogApi' -name 'FogJoinTaskRequest' {
    Context 'FogJoinTaskRequest' {
        It 'Initialize-FogJoinTaskRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-FogJoinTaskRequest -Id "TEST_VALUE" -Name "TEST_VALUE" -CheckInTime "TEST_VALUE" -HostID "TEST_VALUE" -StateID "TEST_VALUE" -IsForced "TEST_VALUE" -ScheduledStartTime "TEST_VALUE" -TypeID "TEST_VALUE" -Pct "TEST_VALUE" -Bpm "TEST_VALUE" -TimeElapsed "TEST_VALUE" -TimeRemaining "TEST_VALUE" -DataCopied "TEST_VALUE" -Percent "TEST_VALUE" -DataTotal "TEST_VALUE" -StoragegroupID "TEST_VALUE" -StoragenodeID "TEST_VALUE" -NFSFailures "TEST_VALUE" -NFSLastMemberID "TEST_VALUE" -Shutdown "TEST_VALUE" -Passreset "TEST_VALUE" -IsDebug "TEST_VALUE" -ImageID "TEST_VALUE" -Wol "TEST_VALUE" -Bypassbitlocker "TEST_VALUE" -StateChangedTime "TEST_VALUE" -Ids "TEST_VALUE"
            #$NewObject | Should -BeOfType JoinTaskRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
