function Find-FogSite {
    <#
    .SYNOPSIS
    Finds site objects matching a search term.

    .DESCRIPTION
    Matches the term across the site class fields and returns the same envelope
    a list does.

    .PARAMETER stringToSearch
    Text to match across the class fields.

    .EXAMPLE
    Find-FogSite -stringToSearch 'Example'

    Returns every site matching "Example".

    Expected output:
    [ { "id": 1, "name": "ExampleSite" } ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'searchSite'
    (GET /site/search/{item}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'site.view' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$stringToSearch
    )

    process {
        Write-Verbose "searching fog site for $stringToSearch";
        return (Find-FogObject -coreObject site -stringToSearch $stringToSearch).data;
    }

}
