function Find-FogHostAutoLogout {
    <#
    .SYNOPSIS
    Finds hostautologout objects matching a search term.

    .DESCRIPTION
    Matches the term across the hostautologout class fields and returns the same envelope
    a list does.

    .PARAMETER stringToSearch
    Text to match across the class fields.

    .EXAMPLE
    Find-FogHostAutoLogout -stringToSearch 'Example'

    Returns every hostautologout matching "Example".

    Expected output:
    [ { "id": 1 } ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'searchHostautologout'
    (GET /hostautologout/search/{item}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'host.view' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$stringToSearch
    )

    process {
        Write-Verbose "searching fog hostautologout for $stringToSearch";
        return (Add-FogTypeName -InputObject (Find-FogObject -coreObject hostautologout -stringToSearch $stringToSearch).data -TypeName 'FogApi.Hostautologout');
    }

}
