function Find-FogPlugin {
    <#
    .SYNOPSIS
    Finds plugin objects matching a search term.

    .DESCRIPTION
    Matches the term across the plugin class fields and returns the same envelope
    a list does.

    .PARAMETER stringToSearch
    Text to match across the class fields.

    .EXAMPLE
    Find-FogPlugin -stringToSearch 'Example'

    Returns every plugin matching "Example".

    Expected output:
    [ { "id": 1, "name": "ExamplePlugin" } ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'searchPlugin'
    (GET /plugin/search/{item}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'plugin.view' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$stringToSearch
    )

    process {
        Write-Verbose "searching fog plugin for $stringToSearch";
        return (Find-FogObject -coreObject plugin -stringToSearch $stringToSearch).data;
    }

}
