function Find-FogUserGroup {
    <#
    .SYNOPSIS
    Finds usergroup objects matching a search term.

    .DESCRIPTION
    Matches the term across the usergroup class fields and returns the same envelope
    a list does.

    .PARAMETER stringToSearch
    Text to match across the class fields.

    .EXAMPLE
    Find-FogUserGroup -stringToSearch 'Example'

    Returns every usergroup matching "Example".

    Expected output:
    [ { "id": 1, "name": "ExampleUsergroup" } ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'searchUsergroup'
    (GET /usergroup/search/{item}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'usergroup.view' permission.
    FOG 1.6 only; FOG 1.5 does not serve this operation.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$stringToSearch
    )

    process {
        Write-Verbose "searching fog usergroup for $stringToSearch";
        return (Add-FogTypeName -InputObject (Find-FogObject -coreObject usergroup -stringToSearch $stringToSearch).data -TypeName 'FogApi.Usergroup');
    }

}
