function Find-FogSnapinTask {
    <#
    .SYNOPSIS
    Finds snapintask objects matching a search term.

    .DESCRIPTION
    Matches the term across the snapintask class fields and returns the same envelope
    a list does.

    .PARAMETER stringToSearch
    Text to match across the class fields.

    .EXAMPLE
    Find-FogSnapinTask -stringToSearch 'Example'

    Returns every snapintask matching "Example".

    Expected output:
    [ { "id": 1 } ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'searchSnapintask'
    (GET /snapintask/search/{item}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'task.view' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$stringToSearch
    )

    process {
        Write-Verbose "searching fog snapintask for $stringToSearch";
        return (Find-FogObject -coreObject snapintask -stringToSearch $stringToSearch).data;
    }

}
