function Find-FogModule {
    <#
    .SYNOPSIS
    Finds module objects matching a search term.

    .DESCRIPTION
    Matches the term across the module class fields and returns the same envelope
    a list does.

    .PARAMETER stringToSearch
    Text to match across the class fields.

    .EXAMPLE
    Find-FogModule -stringToSearch 'Example'

    Returns every module matching "Example".

    Expected output:
    [ { "id": 1, "name": "hostnameChanger" } ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'searchModule'
    (GET /module/search/{item}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'module.view' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$stringToSearch
    )

    process {
        Write-Verbose "searching fog module for $stringToSearch";
        return (Add-FogTypeName -InputObject (Find-FogObject -coreObject module -stringToSearch $stringToSearch).data -TypeName 'FogApi.Module');
    }

}
