function Find-FogUser {
    <#
    .SYNOPSIS
    Finds user objects matching a search term.

    .DESCRIPTION
    Matches the term across the user class fields and returns the same envelope
    a list does.

    .PARAMETER stringToSearch
    Text to match across the class fields.

    .EXAMPLE
    Find-FogUser -stringToSearch 'Example'

    Returns every user matching "Example".

    Expected output:
    [ { "id": 1, "name": "ExampleUser" } ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'searchUser'
    (GET /user/search/{item}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'user.view' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$stringToSearch
    )

    process {
        Write-Verbose "searching fog user for $stringToSearch";
        return (Find-FogObject -coreObject user -stringToSearch $stringToSearch).data;
    }

}
