function Find-FogImageType {
    <#
    .SYNOPSIS
    Finds imagetype objects matching a search term.

    .DESCRIPTION
    Matches the term across the imagetype class fields and returns the same envelope
    a list does.

    .PARAMETER stringToSearch
    Text to match across the class fields.

    .EXAMPLE
    Find-FogImageType -stringToSearch 'Example'

    Returns every imagetype matching "Example".

    Expected output:
    [ { "id": 1, "name": "ExampleImagetype" } ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'searchImagetype'
    (GET /imagetype/search/{item}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'image.view' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$stringToSearch
    )

    process {
        Write-Verbose "searching fog imagetype for $stringToSearch";
        return (Find-FogObject -coreObject imagetype -stringToSearch $stringToSearch).data;
    }

}
