function Get-FogSnapinGroupAssociation {
    <#
    .SYNOPSIS
    Gets snapingroupassociation objects from the fog server.

    .DESCRIPTION
    With no parameters, returns every snapingroupassociation, the way Get-Process returns every
    process. -All says the same thing explicitly. -id or -name narrows to one.

    On FOG 1.6 a full list is paged automatically and every page is followed, so
    the result is complete rather than capped at the server's row limit (10000 rows).

    -Count, -NamesOnly and -IdsOnly ask the cheaper questions the server can answer
    without sending the rows. All three are FOG 1.6 only.

    .PARAMETER All
    Return every snapingroupassociation. The default when no other parameter is given.

    .PARAMETER id
    The id of a single snapingroupassociation. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER First
    Return at most this many objects.

    .PARAMETER Skip
    Skip this many objects before returning any.

    .PARAMETER PageSize
    Rows to request per page. Ignored on FOG 1.5, which does not page.

    .PARAMETER NoAutoPage
    Return only the first page instead of following nextUrl.

    .PARAMETER Count
    Return only how many there are. Ignores paging and reports the true total.

    .PARAMETER NamesOnly
    Return only id and name pairs. Unpaged and uncapped server side.

    .PARAMETER IdsOnly
    Return only the ids, as a bare array. Unpaged and uncapped server side.

    .EXAMPLE
    Get-FogSnapinGroupAssociation

    Returns every snapingroupassociation.

    Expected output:
    [ { "id": 1 } ]

    .EXAMPLE
    Get-FogSnapinGroupAssociation -id 1

    Returns one snapingroupassociation by id. Fields the list withholds are returned here.

    Expected output:
    { "id": 1 }

    .EXAMPLE
    Get-FogSnapinGroupAssociation -Count

    Asks how many snapingroupassociation objects exist without transferring any of them.

    Expected output:
    { "total": 1 }

    .EXAMPLE
    Get-FogSnapinGroupAssociation -NamesOnly

    Returns id and name pairs only.

    Expected output:
    [ { "id": 1 } ]

    .EXAMPLE
    Get-FogSnapinGroupAssociation -IdsOnly

    Returns just the ids, the cheapest way to enumerate snapingroupassociation.

    Expected output:
    [ 1 ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'indivSnapingroupassociation'
    (GET /snapingroupassociation/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'snapin.view' permission.
    #>

    [CmdletBinding(DefaultParameterSetName='all')]
    [Alias('Get-FogSnapinGroupAssociations')]
    param (
        [Parameter(ParameterSetName='byId',Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter(ParameterSetName='all')]
        [switch]$All,
        [Parameter(ParameterSetName='all')]
        [int]$First,
        [Parameter(ParameterSetName='all')]
        [int]$Skip,
        [Parameter(ParameterSetName='all')]
        [int]$PageSize = 1000,
        [Parameter(ParameterSetName='all')]
        [switch]$NoAutoPage,
        [Parameter(ParameterSetName='count',Mandatory=$true)]
        [switch]$Count,
        [Parameter(ParameterSetName='names',Mandatory=$true)]
        [switch]$NamesOnly,
        [Parameter(ParameterSetName='ids',Mandatory=$true)]
        [switch]$IdsOnly
    )

    process {
        switch ($PSCmdlet.ParameterSetName) {
            'byId' {
                # An id, or an object carrying one, so a result from one cmdlet pipes
                # straight into another.
                $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
                Write-Verbose "getting fog snapingroupassociation $objectId";
                # No .data: Get-FogObject only wraps a list, and a fetch by id returns
                # the bare object.
                return (Add-FogTypeName -InputObject (Get-FogObject -type object -coreObject snapingroupassociation -IDofObject $objectId) -TypeName 'FogApi.Snapingroupassociation');
            }
            'count'  { return Get-FogObject -type object -coreObject snapingroupassociation -subPath count; }
            'names'  { return Get-FogObject -type object -coreObject snapingroupassociation -subPath names; }
            'ids'    { return Get-FogObject -type object -coreObject snapingroupassociation -subPath ids; }
            default {
                Write-Verbose "getting all fog snapingroupassociation objects";
                $splat = @{ type = 'object'; coreObject = 'snapingroupassociation' };
                foreach ($p in @('First','Skip','PageSize','NoAutoPage')) {
                    if ($PSBoundParameters.ContainsKey($p)) { $splat[$p] = $PSBoundParameters[$p]; }
                }
                return (Add-FogTypeName -InputObject (Get-FogObject @splat).data -TypeName 'FogApi.Snapingroupassociation');
            }
        }
    }

}
