function Get-FogRoleUserAssociation {
    <#
    .SYNOPSIS
    Gets roleuserassociation objects from the fog server.

    .DESCRIPTION
    With no parameters, returns every roleuserassociation, the way Get-Process returns every
    process. -All says the same thing explicitly. -id or -name narrows to one.

    On FOG 1.6 a full list is paged automatically and every page is followed, so
    the result is complete rather than capped at the server's row limit (10000 rows).

    -name is a client side convenience: FOG has no get-by-name route, because the
    router constrains the id segment to an integer. It resolves through the class's
    id/name listing, which is unpaged and uncapped, then fetches the match by id.
    Two small requests rather than one large one.

    -Count, -NamesOnly and -IdsOnly ask the cheaper questions the server can answer
    without sending the rows. All three are FOG 1.6 only.

    .PARAMETER All
    Return every roleuserassociation. The default when no other parameter is given.

    .PARAMETER id
    The id of a single roleuserassociation. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    The name of a single roleuserassociation. Resolved client side; a name matching nothing returns nothing, and an ambiguous one warns.

    .PARAMETER First
    Return at most this many objects.

    .PARAMETER Skip
    Skip this many objects before returning any.

    .PARAMETER PageSize
    Rows to request per page. Ignored on FOG 1.5, which does not page.

    .PARAMETER NoAutoPage
    Return only the first page instead of following nextUrl.

    .PARAMETER Count
    Return only how many there are. Ignores paging and reports the true total.

    .PARAMETER NamesOnly
    Return only id and name pairs. Unpaged and uncapped server side.

    .PARAMETER IdsOnly
    Return only the ids, as a bare array. Unpaged and uncapped server side.

    .EXAMPLE
    Get-FogRoleUserAssociation

    Returns every roleuserassociation.

    Expected output:
    [ { "id": 1, "name": "ExampleRoleuserassociation" } ]

    .EXAMPLE
    Get-FogRoleUserAssociation -id 1

    Returns one roleuserassociation by id. Fields the list withholds are returned here.

    Expected output:
    { "id": 1, "name": "ExampleRoleuserassociation" }

    .EXAMPLE
    Get-FogRoleUserAssociation -name 'ExampleRoleuserassociation'

    Returns one roleuserassociation by name.

    Expected output:
    { "id": 1, "name": "ExampleRoleuserassociation" }

    .EXAMPLE
    Get-FogRoleUserAssociation -Count

    Asks how many roleuserassociation objects exist without transferring any of them.

    Expected output:
    { "total": 1 }

    .EXAMPLE
    Get-FogRoleUserAssociation -NamesOnly

    Returns id and name pairs only.

    Expected output:
    [ { "id": 1, "name": "ExampleRoleuserassociation" } ]

    .EXAMPLE
    Get-FogRoleUserAssociation -IdsOnly

    Returns just the ids, the cheapest way to enumerate roleuserassociation.

    Expected output:
    [ 1 ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'indivRoleuserassociation'
    (GET /roleuserassociation/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'role.view' permission.
    FOG 1.6 only; FOG 1.5 does not serve this operation.
    #>

    [CmdletBinding(DefaultParameterSetName='all')]
    [Alias('Get-FogRoleUserAssociations')]
    param (
        [Parameter(ParameterSetName='byId',Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter(ParameterSetName='byName',Mandatory=$true,Position=0)]
        [string]$name,
        [Parameter(ParameterSetName='all')]
        [switch]$All,
        [Parameter(ParameterSetName='all')]
        [int]$First,
        [Parameter(ParameterSetName='all')]
        [int]$Skip,
        [Parameter(ParameterSetName='all')]
        [int]$PageSize = 1000,
        [Parameter(ParameterSetName='all')]
        [switch]$NoAutoPage,
        [Parameter(ParameterSetName='count',Mandatory=$true)]
        [switch]$Count,
        [Parameter(ParameterSetName='names',Mandatory=$true)]
        [switch]$NamesOnly,
        [Parameter(ParameterSetName='ids',Mandatory=$true)]
        [switch]$IdsOnly
    )

    process {
        switch ($PSCmdlet.ParameterSetName) {
            'byId' {
                # An id, or an object carrying one, so a result from one cmdlet pipes
                # straight into another.
                $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
                Write-Verbose "getting fog roleuserassociation $objectId";
                # No .data: Get-FogObject only wraps a list, and a fetch by id returns
                # the bare object.
                return Get-FogObject -type object -coreObject roleuserassociation -IDofObject $objectId;
            }
            'byName' {
                Write-Verbose "resolving fog roleuserassociation named $name";
                # FOG has no get-by-name route, so this resolves the id first. The
                # names listing is unpaged and uncapped, which makes it cheaper than
                # fetching the whole table and far more exact than a search, which
                # matches the term across every field.
                try {
                    $pairs = Get-FogObject -type object -coreObject roleuserassociation -subPath names;
                } catch {
                    # FOG 1.5 has no names route. Fall back to search rather than
                    # probing the version, which would cost a round trip on 1.6 too.
                    Write-Verbose "names route unavailable, falling back to search";
                    $pairs = (Find-FogObject -coreObject roleuserassociation -stringToSearch $name).data;
                }
                $match = @($pairs | Where-Object { $_.name -eq $name });
                if ($match.Count -eq 0) {
                    Write-Warning "no fog roleuserassociation is named '$name'";
                    return $null;
                }
                if ($match.Count -gt 1) {
                    Write-Warning "$($match.Count) fog roleuserassociation objects are named '$name'; returning the first. Use -id to be unambiguous.";
                }
                return Get-FogObject -type object -coreObject roleuserassociation -IDofObject $match[0].id;
            }
            'count'  { return Get-FogObject -type object -coreObject roleuserassociation -subPath count; }
            'names'  { return Get-FogObject -type object -coreObject roleuserassociation -subPath names; }
            'ids'    { return Get-FogObject -type object -coreObject roleuserassociation -subPath ids; }
            default {
                Write-Verbose "getting all fog roleuserassociation objects";
                $splat = @{ type = 'object'; coreObject = 'roleuserassociation' };
                foreach ($p in @('First','Skip','PageSize','NoAutoPage')) {
                    if ($PSBoundParameters.ContainsKey($p)) { $splat[$p] = $PSBoundParameters[$p]; }
                }
                return (Get-FogObject @splat).data;
            }
        }
    }

}
