function Get-FogSite {
    <#
    .SYNOPSIS
    Gets site objects from the fog server.

    .DESCRIPTION
    With no parameters, returns every site, the way Get-Process returns every
    process. -All says the same thing explicitly. -id or -name narrows to one.

    On FOG 1.6 a full list is paged automatically and every page is followed, so
    the result is complete rather than capped at the server's row limit (10000 rows).

    -name is a client side convenience: FOG has no get-by-name route, because the
    router constrains the id segment to an integer. It resolves through the class's
    id/name listing, which is unpaged and uncapped, then fetches the match by id.
    Two small requests rather than one large one.

    -Count, -NamesOnly and -IdsOnly ask the cheaper questions the server can answer
    without sending the rows. All three are FOG 1.6 only.

    .PARAMETER All
    Return every site. The default when no other parameter is given.

    .PARAMETER id
    The id of a single site. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    The name of a single site. Resolved client side; a name matching nothing returns nothing, and an ambiguous one warns.

    .PARAMETER First
    Return at most this many objects.

    .PARAMETER Skip
    Skip this many objects before returning any.

    .PARAMETER PageSize
    Rows to request per page. Ignored on FOG 1.5, which does not page.

    .PARAMETER NoAutoPage
    Return only the first page instead of following nextUrl.

    .PARAMETER Count
    Return only how many there are. Ignores paging and reports the true total.

    .PARAMETER NamesOnly
    Return only id and name pairs. Unpaged and uncapped server side.

    .PARAMETER IdsOnly
    Return only the ids, as a bare array. Unpaged and uncapped server side.

    .EXAMPLE
    Get-FogSite

    Returns every site.

    Expected output:
    [ { "id": 1, "name": "ExampleSite" } ]

    .EXAMPLE
    Get-FogSite -id 1

    Returns one site by id. Fields the list withholds are returned here.

    Expected output:
    { "id": 1, "name": "ExampleSite" }

    .EXAMPLE
    Get-FogSite -name 'ExampleSite'

    Returns one site by name.

    Expected output:
    { "id": 1, "name": "ExampleSite" }

    .EXAMPLE
    Get-FogSite -Count

    Asks how many site objects exist without transferring any of them.

    Expected output:
    { "total": 1 }

    .EXAMPLE
    Get-FogSite -NamesOnly

    Returns id and name pairs only.

    Expected output:
    [ { "id": 1, "name": "ExampleSite" } ]

    .EXAMPLE
    Get-FogSite -IdsOnly

    Returns just the ids, the cheapest way to enumerate site.

    Expected output:
    [ 1 ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'indivSite'
    (GET /site/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'site.view' permission.
    #>

    [CmdletBinding(DefaultParameterSetName='all')]
    [Alias('Get-FogSites')]
    param (
        [Parameter(ParameterSetName='byId',Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter(ParameterSetName='byName',Mandatory=$true,Position=0)]
        [string]$name,
        [Parameter(ParameterSetName='all')]
        [switch]$All,
        [Parameter(ParameterSetName='all')]
        [int]$First,
        [Parameter(ParameterSetName='all')]
        [int]$Skip,
        [Parameter(ParameterSetName='all')]
        [int]$PageSize = 1000,
        [Parameter(ParameterSetName='all')]
        [switch]$NoAutoPage,
        [Parameter(ParameterSetName='count',Mandatory=$true)]
        [switch]$Count,
        [Parameter(ParameterSetName='names',Mandatory=$true)]
        [switch]$NamesOnly,
        [Parameter(ParameterSetName='ids',Mandatory=$true)]
        [switch]$IdsOnly
    )

    process {
        switch ($PSCmdlet.ParameterSetName) {
            'byId' {
                # An id, or an object carrying one, so a result from one cmdlet pipes
                # straight into another.
                $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
                Write-Verbose "getting fog site $objectId";
                # No .data: Get-FogObject only wraps a list, and a fetch by id returns
                # the bare object.
                return (Add-FogTypeName -InputObject (Get-FogObject -type object -coreObject site -IDofObject $objectId) -TypeName 'FogApi.Site');
            }
            'byName' {
                Write-Verbose "resolving fog site named $name";
                # FOG has no get-by-name route, so this resolves the id first. The
                # names listing is unpaged and uncapped, which makes it cheaper than
                # fetching the whole table and far more exact than a search, which
                # matches the term across every field.
                try {
                    $pairs = Get-FogObject -type object -coreObject site -subPath names;
                } catch {
                    # FOG 1.5 has no names route. Fall back to search rather than
                    # probing the version, which would cost a round trip on 1.6 too.
                    Write-Verbose "names route unavailable, falling back to search";
                    $pairs = (Find-FogObject -coreObject site -stringToSearch $name).data;
                }
                $match = @($pairs | Where-Object { $_.name -eq $name });
                if ($match.Count -eq 0) {
                    Write-Warning "no fog site is named '$name'";
                    return $null;
                }
                if ($match.Count -gt 1) {
                    Write-Warning "$($match.Count) fog site objects are named '$name'; returning the first. Use -id to be unambiguous.";
                }
                return (Add-FogTypeName -InputObject (Get-FogObject -type object -coreObject site -IDofObject $match[0].id) -TypeName 'FogApi.Site');
            }
            'count'  { return Get-FogObject -type object -coreObject site -subPath count; }
            'names'  { return Get-FogObject -type object -coreObject site -subPath names; }
            'ids'    { return Get-FogObject -type object -coreObject site -subPath ids; }
            default {
                Write-Verbose "getting all fog site objects";
                $splat = @{ type = 'object'; coreObject = 'site' };
                foreach ($p in @('First','Skip','PageSize','NoAutoPage')) {
                    if ($PSBoundParameters.ContainsKey($p)) { $splat[$p] = $PSBoundParameters[$p]; }
                }
                return (Add-FogTypeName -InputObject (Get-FogObject @splat).data -TypeName 'FogApi.Site');
            }
        }
    }

}
