function Get-FogPrinters {
    <#
    .SYNOPSIS
    Gets every printer on the fog server.

    .DESCRIPTION
    Returns all printer objects. On FOG 1.6 the list is paged automatically and
    every page is followed, so the result is complete rather than capped at the
    server's row limit (10000 rows). Filter the result with Where-Object.

    Three cheaper questions the server can answer without sending the rows are
    switches rather than separate cmdlets: -Count, -NamesOnly and -IdsOnly.
    -NamesOnly and -IdsOnly have no server side row limit at all, which makes
    them the cheap way to enumerate a large table. All three are FOG 1.6 only.

    .PARAMETER First
    Return at most this many objects.

    .PARAMETER Skip
    Skip this many objects before returning any.

    .PARAMETER PageSize
    Rows to request per page. Ignored on FOG 1.5, which does not page.

    .PARAMETER NoAutoPage
    Return only the first page instead of following nextUrl.

    .PARAMETER Count
    Return only how many printer objects there are, as a total. Ignores paging and reports the true total.

    .PARAMETER NamesOnly
    Return only id and name pairs. Unpaged and uncapped server side.

    .PARAMETER IdsOnly
    Return only the ids, as a bare array. Unpaged and uncapped server side.

    .EXAMPLE
    Get-FogPrinters

    Returns an array of every printer.

    Expected output:
    [ { "id": 1, "name": "ExamplePrinter" } ]

    .EXAMPLE
    Get-FogPrinters -Count

    Asks how many printer objects exist without transferring any of them.

    Expected output:
    { "total": 1 }

    .EXAMPLE
    Get-FogPrinters -NamesOnly

    Returns id and name pairs only.

    Expected output:
    [ { "id": 1, "name": "ExamplePrinter" } ]

    .EXAMPLE
    Get-FogPrinters -IdsOnly

    Returns just the ids, which is the cheapest way to enumerate printer.

    Expected output:
    [ 1 ]

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'listPrinter'
    (GET /printer) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'printer.view' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(ParameterSetName='page')]
        [int]$First,
        [Parameter(ParameterSetName='page')]
        [int]$Skip,
        [Parameter(ParameterSetName='page')]
        [int]$PageSize = 1000,
        [Parameter(ParameterSetName='page')]
        [switch]$NoAutoPage,
        [Parameter(Mandatory=$true,ParameterSetName='count')]
        [switch]$Count,
        [Parameter(Mandatory=$true,ParameterSetName='names')]
        [switch]$NamesOnly,
        [Parameter(Mandatory=$true,ParameterSetName='ids')]
        [switch]$IdsOnly
    )

    process {
        $subPath = switch ($PSCmdlet.ParameterSetName) {
            'count' { 'count' }
            'names' { 'names' }
            'ids'   { 'ids' }
            default  { $null }
        }
        if ($subPath) {
            Write-Verbose "getting fog printer $subPath";
            # Returned exactly as the server sent it. None of these three carries
            # a list envelope, so there is no .data to unwrap.
            return Get-FogObject -type object -coreObject printer -subPath $subPath;
        }
        Write-Verbose "getting all fog printer objects";
        $splat = @{ type = 'object'; coreObject = 'printer' };
        foreach ($p in @('First','Skip','PageSize','NoAutoPage')) {
            if ($PSBoundParameters.ContainsKey($p)) { $splat[$p] = $PSBoundParameters[$p]; }
        }
        return (Get-FogObject @splat).data;
    }

}
