function New-FogStorageNode {
    <#
    .SYNOPSIS
    Creates a storagenode.

    .DESCRIPTION
    Creates a new storagenode object. Every writable field of the class is a named
    parameter, with the length and value constraints the server itself declares.
    Use -settings for a field a newer server has added that this module does not
    yet know about.

    .PARAMETER name
    Sets the name field (column ngmMemberName).

    .PARAMETER description
    Sets the description field (column ngmMemberDescription).

    .PARAMETER isMaster
    Sets the isMaster field (column ngmIsMasterNode).

    .PARAMETER storagegroupID
    Sets the storagegroupID field (column ngmGroupID).

    .PARAMETER isEnabled
    Sets the isEnabled field (column ngmIsEnabled).

    .PARAMETER isGraphEnabled
    Sets the isGraphEnabled field (column ngmGraphEnabled).

    .PARAMETER path
    Sets the path field (column ngmRootPath).

    .PARAMETER ftppath
    Sets the ftppath field (column ngmFTPPath).

    .PARAMETER bitrate
    Sets the bitrate field (column ngmMaxBitrate).

    .PARAMETER helloInterval
    Sets the helloInterval field (column ngmHelloInterval).

    .PARAMETER snapinpath
    Sets the snapinpath field (column ngmSnapinPath).

    .PARAMETER sslpath
    Sets the sslpath field (column ngmSSLPath).

    .PARAMETER ip
    Sets the ip field (column ngmHostname).

    .PARAMETER maxClients
    Sets the maxClients field (column ngmMaxClients).

    .PARAMETER user
    Sets the user field (column ngmUser).

    .PARAMETER pass
    Sets the pass field (column ngmPass).

    .PARAMETER key
    Sets the key field (column ngmKey).

    .PARAMETER interface
    Sets the interface field (column ngmInterface).

    .PARAMETER bandwidth
    Sets the bandwidth field (column ngmBandwidthLimit).

    .PARAMETER webroot
    Sets the webroot field (column ngmWebroot).

    .PARAMETER graphcolor
    Sets the graphcolor field (column ngmGraphColor).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters. An escape hatch for fields not yet modelled.

    .EXAMPLE
    New-FogStorageNode -path 'example' -ftppath 'example' -ip 'example' -user 'example' -pass 'example'

    Creates a storagenode and returns the created object.

    Expected output:
    { "id": 1, "path": "example", "ftppath": "example", "ip": "example", "user": "example", "pass": "example" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'createStoragenode'
    (POST /storagenode) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'storagenode.create' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$isMaster,
        [Parameter()]
        [int]$storagegroupID,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$isEnabled,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$isGraphEnabled,
        [Parameter(Mandatory=$true)]
        [string]$path,
        [Parameter(Mandatory=$true)]
        [string]$ftppath,
        [Parameter()]
        [ValidateLength(0,25)]
        [string]$bitrate,
        [Parameter()]
        [ValidateLength(0,8)]
        [string]$helloInterval,
        [Parameter()]
        [string]$snapinpath,
        [Parameter()]
        [string]$sslpath,
        [Parameter(Mandatory=$true)]
        [ValidateLength(0,250)]
        [string]$ip,
        [Parameter()]
        [int]$maxClients,
        [Parameter(Mandatory=$true)]
        [ValidateLength(0,250)]
        [string]$user,
        [Parameter(Mandatory=$true)]
        [ValidateLength(0,250)]
        [string]$pass,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$key,
        [Parameter()]
        [ValidateLength(0,25)]
        [string]$interface,
        [Parameter()]
        [int]$bandwidth,
        [Parameter()]
        [string]$webroot,
        [Parameter()]
        [ValidateLength(0,6)]
        [string]$graphcolor,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('isMaster')) { $payload.isMaster = $isMaster; }
        if ($PSBoundParameters.ContainsKey('storagegroupID')) { $payload.storagegroupID = $storagegroupID; }
        if ($PSBoundParameters.ContainsKey('isEnabled')) { $payload.isEnabled = $isEnabled; }
        if ($PSBoundParameters.ContainsKey('isGraphEnabled')) { $payload.isGraphEnabled = $isGraphEnabled; }
        if ($PSBoundParameters.ContainsKey('path')) { $payload.path = $path; }
        if ($PSBoundParameters.ContainsKey('ftppath')) { $payload.ftppath = $ftppath; }
        if ($PSBoundParameters.ContainsKey('bitrate')) { $payload.bitrate = $bitrate; }
        if ($PSBoundParameters.ContainsKey('helloInterval')) { $payload.helloInterval = $helloInterval; }
        if ($PSBoundParameters.ContainsKey('snapinpath')) { $payload.snapinpath = $snapinpath; }
        if ($PSBoundParameters.ContainsKey('sslpath')) { $payload.sslpath = $sslpath; }
        if ($PSBoundParameters.ContainsKey('ip')) { $payload.ip = $ip; }
        if ($PSBoundParameters.ContainsKey('maxClients')) { $payload.maxClients = $maxClients; }
        if ($PSBoundParameters.ContainsKey('user')) { $payload.user = $user; }
        if ($PSBoundParameters.ContainsKey('pass')) { $payload.pass = $pass; }
        if ($PSBoundParameters.ContainsKey('key')) { $payload.key = $key; }
        if ($PSBoundParameters.ContainsKey('interface')) { $payload.interface = $interface; }
        if ($PSBoundParameters.ContainsKey('bandwidth')) { $payload.bandwidth = $bandwidth; }
        if ($PSBoundParameters.ContainsKey('webroot')) { $payload.webroot = $webroot; }
        if ($PSBoundParameters.ContainsKey('graphcolor')) { $payload.graphcolor = $graphcolor; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "creating fog storagenode";
        return (Add-FogTypeName -InputObject (New-FogObject -type object -coreObject storagenode -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Storagenode');
    }

}
