function New-FogTask {
    <#
    .SYNOPSIS
    Creates a task.

    .DESCRIPTION
    Creates a new task object. Every writable field of the class is a named
    parameter, with the length and value constraints the server itself declares.
    Use -settings for a field a newer server has added that this module does not
    yet know about.

    .PARAMETER name
    Sets the name field (column taskName).

    .PARAMETER checkInTime
    Sets the checkInTime field (column taskCheckIn).

    .PARAMETER hostID
    Sets the hostID field (column taskHostID).

    .PARAMETER stateID
    Sets the stateID field (column taskStateID).

    .PARAMETER isForced
    Sets the isForced field (column taskForce).

    .PARAMETER scheduledStartTime
    Sets the scheduledStartTime field (column taskScheduledStartTime).

    .PARAMETER typeID
    Sets the typeID field (column taskTypeID).

    .PARAMETER storagegroupID
    Sets the storagegroupID field (column taskNFSGroupID).

    .PARAMETER storagenodeID
    Sets the storagenodeID field (column taskNFSMemberID).

    .PARAMETER NFSFailures
    Sets the NFSFailures field (column taskNFSFailures).

    .PARAMETER NFSLastMemberID
    Sets the NFSLastMemberID field (column taskLastMemberID).

    .PARAMETER shutdown
    Sets the shutdown field (column taskShutdown).

    .PARAMETER passreset
    Sets the passreset field (column taskPassreset).

    .PARAMETER isDebug
    Sets the isDebug field (column taskIsDebug).

    .PARAMETER imageID
    Sets the imageID field (column taskImageID).

    .PARAMETER wol
    Sets the wol field (column taskWOL).

    .PARAMETER bypassbitlocker
    Sets the bypassbitlocker field (column taskBypassBitlocker).

    .PARAMETER stateChangedTime
    Sets the stateChangedTime field (column taskStateChangedTime).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters. An escape hatch for fields not yet modelled.

    .EXAMPLE
    New-FogTask -hostID 1 -typeID 1

    Creates a task and returns the created object.

    Expected output:
    { "id": 1, "hostID": 1, "typeID": 1 }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'createTask'
    (POST /task) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'task.create' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$name,
        [Parameter()]
        [string]$checkInTime,
        [Parameter(Mandatory=$true)]
        [int]$hostID,
        [Parameter()]
        [int]$stateID,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$isForced,
        [Parameter()]
        [string]$scheduledStartTime,
        [Parameter(Mandatory=$true)]
        [int]$typeID,
        [Parameter()]
        [int]$storagegroupID,
        [Parameter()]
        [int]$storagenodeID,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$NFSFailures,
        [Parameter()]
        [int]$NFSLastMemberID,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$shutdown,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$passreset,
        [Parameter()]
        [int]$isDebug,
        [Parameter()]
        [int]$imageID,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$wol,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$bypassbitlocker,
        [Parameter()]
        [string]$stateChangedTime,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('checkInTime')) { $payload.checkInTime = $checkInTime; }
        if ($PSBoundParameters.ContainsKey('hostID')) { $payload.hostID = $hostID; }
        if ($PSBoundParameters.ContainsKey('stateID')) { $payload.stateID = $stateID; }
        if ($PSBoundParameters.ContainsKey('isForced')) { $payload.isForced = $isForced; }
        if ($PSBoundParameters.ContainsKey('scheduledStartTime')) { $payload.scheduledStartTime = $scheduledStartTime; }
        if ($PSBoundParameters.ContainsKey('typeID')) { $payload.typeID = $typeID; }
        if ($PSBoundParameters.ContainsKey('storagegroupID')) { $payload.storagegroupID = $storagegroupID; }
        if ($PSBoundParameters.ContainsKey('storagenodeID')) { $payload.storagenodeID = $storagenodeID; }
        if ($PSBoundParameters.ContainsKey('NFSFailures')) { $payload.NFSFailures = $NFSFailures; }
        if ($PSBoundParameters.ContainsKey('NFSLastMemberID')) { $payload.NFSLastMemberID = $NFSLastMemberID; }
        if ($PSBoundParameters.ContainsKey('shutdown')) { $payload.shutdown = $shutdown; }
        if ($PSBoundParameters.ContainsKey('passreset')) { $payload.passreset = $passreset; }
        if ($PSBoundParameters.ContainsKey('isDebug')) { $payload.isDebug = $isDebug; }
        if ($PSBoundParameters.ContainsKey('imageID')) { $payload.imageID = $imageID; }
        if ($PSBoundParameters.ContainsKey('wol')) { $payload.wol = $wol; }
        if ($PSBoundParameters.ContainsKey('bypassbitlocker')) { $payload.bypassbitlocker = $bypassbitlocker; }
        if ($PSBoundParameters.ContainsKey('stateChangedTime')) { $payload.stateChangedTime = $stateChangedTime; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "creating fog task";
        return New-FogObject -type object -coreObject task -jsonData ($payload | ConvertTo-Json -Compress);
    }

}
