function New-FogGroup {
    <#
    .SYNOPSIS
    Creates a group.

    .DESCRIPTION
    Creates a new group object. Every writable field of the class is a named
    parameter, with the length and value constraints the server itself declares.
    Use -settings for a field a newer server has added that this module does not
    yet know about.

    .PARAMETER name
    Sets the name field (column groupName).

    .PARAMETER description
    Sets the description field (column groupDesc).

    .PARAMETER building
    Sets the building field (column groupBuilding).

    .PARAMETER kernel
    Sets the kernel field (column groupKernel).

    .PARAMETER kernelArgs
    Sets the kernelArgs field (column groupKernelArgs).

    .PARAMETER kernelDevice
    Sets the kernelDevice field (column groupPrimaryDisk).

    .PARAMETER init
    Sets the init field (column groupInit).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters. An escape hatch for fields not yet modelled.

    .EXAMPLE
    New-FogGroup -name 'ExampleGroup'

    Creates a group and returns the created object.

    Expected output:
    { "id": 1, "name": "ExampleGroup" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'createGroup'
    (POST /group) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'group.create' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true)]
        [ValidateLength(0,50)]
        [Alias('groupName')]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter()]
        [int]$building,
        [Parameter()]
        [ValidateLength(0,255)]
        [string]$kernel,
        [Parameter()]
        [ValidateLength(0,255)]
        [string]$kernelArgs,
        [Parameter()]
        [ValidateLength(0,255)]
        [string]$kernelDevice,
        [Parameter()]
        [string]$init,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('building')) { $payload.building = $building; }
        if ($PSBoundParameters.ContainsKey('kernel')) { $payload.kernel = $kernel; }
        if ($PSBoundParameters.ContainsKey('kernelArgs')) { $payload.kernelArgs = $kernelArgs; }
        if ($PSBoundParameters.ContainsKey('kernelDevice')) { $payload.kernelDevice = $kernelDevice; }
        if ($PSBoundParameters.ContainsKey('init')) { $payload.init = $init; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "creating fog group";
        return New-FogObject -type object -coreObject group -jsonData ($payload | ConvertTo-Json -Compress);
    }

}
