function New-FogRoleUserAssociation {
    <#
    .SYNOPSIS
    Creates a roleuserassociation.

    .DESCRIPTION
    Creates a new roleuserassociation object. Every writable field of the class is a named
    parameter, with the length and value constraints the server itself declares.
    Use -settings for a field a newer server has added that this module does not
    yet know about.

    .PARAMETER name
    Sets the name field (column ruaName).

    .PARAMETER roleID
    Sets the roleID field (column ruaRoleID).

    .PARAMETER userID
    Sets the userID field (column ruaUserID).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters. An escape hatch for fields not yet modelled.

    .EXAMPLE
    New-FogRoleUserAssociation -roleID 1 -userID 1

    Creates a roleuserassociation and returns the created object.

    Expected output:
    { "id": 1, "roleID": 1, "userID": 1 }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'createRoleuserassociation'
    (POST /roleuserassociation) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'role.create' permission.
    FOG 1.6 only; FOG 1.5 does not serve this operation.
    #>

    [CmdletBinding()]
    param (
        [Parameter()]
        [ValidateLength(0,60)]
        [string]$name,
        [Parameter(Mandatory=$true)]
        [int]$roleID,
        [Parameter(Mandatory=$true)]
        [int]$userID,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('roleID')) { $payload.roleID = $roleID; }
        if ($PSBoundParameters.ContainsKey('userID')) { $payload.userID = $userID; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "creating fog roleuserassociation";
        return New-FogObject -type object -coreObject roleuserassociation -jsonData ($payload | ConvertTo-Json -Compress);
    }

}
