function New-FogScheduledTask {
    <#
    .SYNOPSIS
    Creates a scheduledtask.

    .DESCRIPTION
    Creates a new scheduledtask object. Every writable field of the class is a named
    parameter, with the length and value constraints the server itself declares.
    Use -settings for a field a newer server has added that this module does not
    yet know about.

    .PARAMETER name
    Sets the name field (column stName).

    .PARAMETER description
    Sets the description field (column stDesc).

    .PARAMETER type
    Sets the type field (column stType).

    .PARAMETER taskTypeID
    Sets the taskTypeID field (column stTaskTypeID).

    .PARAMETER minute
    Sets the minute field (column stMinute).

    .PARAMETER hour
    Sets the hour field (column stHour).

    .PARAMETER dayOfMonth
    Sets the dayOfMonth field (column stDOM).

    .PARAMETER month
    Sets the month field (column stMonth).

    .PARAMETER dayOfWeek
    Sets the dayOfWeek field (column stDOW).

    .PARAMETER isGroupTask
    Sets the isGroupTask field (column stIsGroup).

    .PARAMETER hostID
    Sets the hostID field (column stGroupHostID).

    .PARAMETER shutdown
    Sets the shutdown field (column stShutDown).

    .PARAMETER other1
    Sets the other1 field (column stOther1).

    .PARAMETER other2
    Sets the other2 field (column stOther2).

    .PARAMETER other3
    Sets the other3 field (column stOther3).

    .PARAMETER other4
    Sets the other4 field (column stOther4).

    .PARAMETER other5
    Sets the other5 field (column stOther5).

    .PARAMETER scheduleTime
    Sets the scheduleTime field (column stDateTime).

    .PARAMETER isActive
    Sets the isActive field (column stActive).

    .PARAMETER imageID
    Sets the imageID field (column stImageID).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters. An escape hatch for fields not yet modelled.

    .EXAMPLE
    New-FogScheduledTask -type 'example' -taskTypeID 1 -hostID 1

    Creates a scheduledtask and returns the created object.

    Expected output:
    { "id": 1, "type": "example", "taskTypeID": 1, "hostID": 1 }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'createScheduledtask'
    (POST /scheduledtask) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'task.create' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter(Mandatory=$true)]
        [ValidateLength(0,24)]
        [string]$type,
        [Parameter(Mandatory=$true)]
        [int]$taskTypeID,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$minute,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$hour,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$dayOfMonth,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$month,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$dayOfWeek,
        [Parameter()]
        [ValidateLength(0,2)]
        [string]$isGroupTask,
        [Parameter(Mandatory=$true)]
        [int]$hostID,
        [Parameter()]
        [ValidateLength(0,2)]
        [string]$shutdown,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other1,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other2,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other3,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other4,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other5,
        [Parameter()]
        [int]$scheduleTime,
        [Parameter()]
        [ValidateLength(0,2)]
        [string]$isActive,
        [Parameter()]
        [int]$imageID,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('type')) { $payload.type = $type; }
        if ($PSBoundParameters.ContainsKey('taskTypeID')) { $payload.taskTypeID = $taskTypeID; }
        if ($PSBoundParameters.ContainsKey('minute')) { $payload.minute = $minute; }
        if ($PSBoundParameters.ContainsKey('hour')) { $payload.hour = $hour; }
        if ($PSBoundParameters.ContainsKey('dayOfMonth')) { $payload.dayOfMonth = $dayOfMonth; }
        if ($PSBoundParameters.ContainsKey('month')) { $payload.month = $month; }
        if ($PSBoundParameters.ContainsKey('dayOfWeek')) { $payload.dayOfWeek = $dayOfWeek; }
        if ($PSBoundParameters.ContainsKey('isGroupTask')) { $payload.isGroupTask = $isGroupTask; }
        if ($PSBoundParameters.ContainsKey('hostID')) { $payload.hostID = $hostID; }
        if ($PSBoundParameters.ContainsKey('shutdown')) { $payload.shutdown = $shutdown; }
        if ($PSBoundParameters.ContainsKey('other1')) { $payload.other1 = $other1; }
        if ($PSBoundParameters.ContainsKey('other2')) { $payload.other2 = $other2; }
        if ($PSBoundParameters.ContainsKey('other3')) { $payload.other3 = $other3; }
        if ($PSBoundParameters.ContainsKey('other4')) { $payload.other4 = $other4; }
        if ($PSBoundParameters.ContainsKey('other5')) { $payload.other5 = $other5; }
        if ($PSBoundParameters.ContainsKey('scheduleTime')) { $payload.scheduleTime = $scheduleTime; }
        if ($PSBoundParameters.ContainsKey('isActive')) { $payload.isActive = $isActive; }
        if ($PSBoundParameters.ContainsKey('imageID')) { $payload.imageID = $imageID; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "creating fog scheduledtask";
        return (Add-FogTypeName -InputObject (New-FogObject -type object -coreObject scheduledtask -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Scheduledtask');
    }

}
