function New-FogRoleUserGroupAssociation {
    <#
    .SYNOPSIS
    Creates a roleusergroupassociation.

    .DESCRIPTION
    Creates a new roleusergroupassociation object. Every writable field of the class is a named
    parameter, with the length and value constraints the server itself declares.
    Use -settings for a field a newer server has added that this module does not
    yet know about.

    .PARAMETER name
    Sets the name field (column rugName).

    .PARAMETER usergroupID
    Sets the usergroupID field (column rugGroupID).

    .PARAMETER roleID
    Sets the roleID field (column rugRoleID).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters. An escape hatch for fields not yet modelled.

    .EXAMPLE
    New-FogRoleUserGroupAssociation -usergroupID 1 -roleID 1

    Creates a roleusergroupassociation and returns the created object.

    Expected output:
    { "id": 1, "usergroupID": 1, "roleID": 1 }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'createRoleusergroupassociation'
    (POST /roleusergroupassociation) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'usergroup.create' permission.
    FOG 1.6 only; FOG 1.5 does not serve this operation.
    #>

    [CmdletBinding()]
    param (
        [Parameter()]
        [ValidateLength(0,60)]
        [string]$name,
        [Parameter(Mandatory=$true)]
        [int]$usergroupID,
        [Parameter(Mandatory=$true)]
        [int]$roleID,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('usergroupID')) { $payload.usergroupID = $usergroupID; }
        if ($PSBoundParameters.ContainsKey('roleID')) { $payload.roleID = $roleID; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "creating fog roleusergroupassociation";
        return (Add-FogTypeName -InputObject (New-FogObject -type object -coreObject roleusergroupassociation -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Roleusergroupassociation');
    }

}
