function New-FogMulticastSession {
    <#
    .SYNOPSIS
    Creates a multicastsession.

    .DESCRIPTION
    Creates a new multicastsession object. Every writable field of the class is a named
    parameter, with the length and value constraints the server itself declares.
    Use -settings for a field a newer server has added that this module does not
    yet know about.

    .PARAMETER name
    Sets the name field (column msName).

    .PARAMETER port
    Sets the port field (column msBasePort).

    .PARAMETER logpath
    Sets the logpath field (column msLogPath).

    .PARAMETER image
    Sets the image field (column msImage).

    .PARAMETER clients
    Sets the clients field (column msClients).

    .PARAMETER sessclients
    Sets the sessclients field (column msSessClients).

    .PARAMETER interface
    Sets the interface field (column msInterface).

    .PARAMETER starttime
    Sets the starttime field (column msStartDateTime).

    .PARAMETER percent
    Sets the percent field (column msPercent).

    .PARAMETER stateID
    Sets the stateID field (column msState).

    .PARAMETER completetime
    Sets the completetime field (column msCompleteDateTime).

    .PARAMETER isDD
    Sets the isDD field (column msIsDD).

    .PARAMETER storagegroupID
    Sets the storagegroupID field (column msNFSGroupID).

    .PARAMETER shutdown
    Sets the shutdown field (column msShutdown).

    .PARAMETER maxwait
    Sets the maxwait field (column msMaxwait).

    .PARAMETER senderpid
    Sets the senderpid field (column msSenderPID).

    .PARAMETER sendernode
    Sets the sendernode field (column msSenderNode).

    .PARAMETER senderstart
    Sets the senderstart field (column msSenderStart).

    .PARAMETER anon5
    Sets the anon5 field (column msAnon5).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters. An escape hatch for fields not yet modelled.

    .EXAMPLE
    New-FogMulticastSession

    Creates a multicastsession and returns the created object.

    Expected output:
    { "id": 1 }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'createMulticastsession'
    (POST /multicastsession) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'task.create' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$name,
        [Parameter()]
        [int]$port,
        [Parameter()]
        [string]$logpath,
        [Parameter()]
        [string]$image,
        [Parameter()]
        [int]$clients,
        [Parameter()]
        [int]$sessclients,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$interface,
        [Parameter()]
        [string]$starttime,
        [Parameter()]
        [int]$percent,
        [Parameter()]
        [int]$stateID,
        [Parameter()]
        [string]$completetime,
        [Parameter()]
        [int]$isDD,
        [Parameter()]
        [int]$storagegroupID,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$shutdown,
        [Parameter()]
        [int]$maxwait,
        [Parameter()]
        [int]$senderpid,
        [Parameter()]
        [int]$sendernode,
        [Parameter()]
        [string]$senderstart,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$anon5,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('port')) { $payload.port = $port; }
        if ($PSBoundParameters.ContainsKey('logpath')) { $payload.logpath = $logpath; }
        if ($PSBoundParameters.ContainsKey('image')) { $payload.image = $image; }
        if ($PSBoundParameters.ContainsKey('clients')) { $payload.clients = $clients; }
        if ($PSBoundParameters.ContainsKey('sessclients')) { $payload.sessclients = $sessclients; }
        if ($PSBoundParameters.ContainsKey('interface')) { $payload.interface = $interface; }
        if ($PSBoundParameters.ContainsKey('starttime')) { $payload.starttime = $starttime; }
        if ($PSBoundParameters.ContainsKey('percent')) { $payload.percent = $percent; }
        if ($PSBoundParameters.ContainsKey('stateID')) { $payload.stateID = $stateID; }
        if ($PSBoundParameters.ContainsKey('completetime')) { $payload.completetime = $completetime; }
        if ($PSBoundParameters.ContainsKey('isDD')) { $payload.isDD = $isDD; }
        if ($PSBoundParameters.ContainsKey('storagegroupID')) { $payload.storagegroupID = $storagegroupID; }
        if ($PSBoundParameters.ContainsKey('shutdown')) { $payload.shutdown = $shutdown; }
        if ($PSBoundParameters.ContainsKey('maxwait')) { $payload.maxwait = $maxwait; }
        if ($PSBoundParameters.ContainsKey('senderpid')) { $payload.senderpid = $senderpid; }
        if ($PSBoundParameters.ContainsKey('sendernode')) { $payload.sendernode = $sendernode; }
        if ($PSBoundParameters.ContainsKey('senderstart')) { $payload.senderstart = $senderstart; }
        if ($PSBoundParameters.ContainsKey('anon5')) { $payload.anon5 = $anon5; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "creating fog multicastsession";
        return (Add-FogTypeName -InputObject (New-FogObject -type object -coreObject multicastsession -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Multicastsession');
    }

}
