function New-FogImage {
    <#
    .SYNOPSIS
    Creates a image.

    .DESCRIPTION
    Creates a new image object. Every writable field of the class is a named
    parameter, with the length and value constraints the server itself declares.
    Use -settings for a field a newer server has added that this module does not
    yet know about.

    .PARAMETER name
    Sets the name field (column imageName).

    .PARAMETER description
    Sets the description field (column imageDesc).

    .PARAMETER path
    Sets the path field (column imagePath).

    .PARAMETER building
    Sets the building field (column imageBuilding).

    .PARAMETER size
    Sets the size field (column imageSize).

    .PARAMETER imageTypeID
    Sets the imageTypeID field (column imageTypeID).

    .PARAMETER imagePartitionTypeID
    Sets the imagePartitionTypeID field (column imagePartitionTypeID).

    .PARAMETER osID
    Sets the osID field (column imageOSID).

    .PARAMETER deployed
    Sets the deployed field (column imageLastDeploy).

    .PARAMETER format
    Sets the format field (column imageFormat).

    .PARAMETER magnet
    Sets the magnet field (column imageMagnetUri).

    .PARAMETER protected
    Sets the protected field (column imageProtect).

    .PARAMETER compress
    Sets the compress field (column imageCompress).

    .PARAMETER isEnabled
    Sets the isEnabled field (column imageEnabled).

    .PARAMETER toReplicate
    Sets the toReplicate field (column imageReplicate).

    .PARAMETER srvsize
    Sets the srvsize field (column imageServerSize).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters. An escape hatch for fields not yet modelled.

    .EXAMPLE
    New-FogImage -name 'ExampleImage' -path 'example' -imageTypeID 1 -osID 1

    Creates a image and returns the created object.

    Expected output:
    { "id": 1, "name": "ExampleImage", "path": "example", "imageTypeID": 1, "osID": 1 }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'createImage'
    (POST /image) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'image.create' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true)]
        [ValidateLength(0,40)]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter(Mandatory=$true)]
        [string]$path,
        [Parameter()]
        [int]$building,
        [Parameter()]
        [ValidateLength(0,255)]
        [string]$size,
        [Parameter(Mandatory=$true)]
        [int]$imageTypeID,
        [Parameter()]
        [int]$imagePartitionTypeID,
        [Parameter(Mandatory=$true)]
        [int]$osID,
        [Parameter()]
        [string]$deployed,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$format,
        [Parameter()]
        [string]$magnet,
        [Parameter()]
        [int]$protected,
        [Parameter()]
        [int]$compress,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$isEnabled,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$toReplicate,
        [Parameter()]
        [int]$srvsize,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('path')) { $payload.path = $path; }
        if ($PSBoundParameters.ContainsKey('building')) { $payload.building = $building; }
        if ($PSBoundParameters.ContainsKey('size')) { $payload.size = $size; }
        if ($PSBoundParameters.ContainsKey('imageTypeID')) { $payload.imageTypeID = $imageTypeID; }
        if ($PSBoundParameters.ContainsKey('imagePartitionTypeID')) { $payload.imagePartitionTypeID = $imagePartitionTypeID; }
        if ($PSBoundParameters.ContainsKey('osID')) { $payload.osID = $osID; }
        if ($PSBoundParameters.ContainsKey('deployed')) { $payload.deployed = $deployed; }
        if ($PSBoundParameters.ContainsKey('format')) { $payload.format = $format; }
        if ($PSBoundParameters.ContainsKey('magnet')) { $payload.magnet = $magnet; }
        if ($PSBoundParameters.ContainsKey('protected')) { $payload.protected = $protected; }
        if ($PSBoundParameters.ContainsKey('compress')) { $payload.compress = $compress; }
        if ($PSBoundParameters.ContainsKey('isEnabled')) { $payload.isEnabled = $isEnabled; }
        if ($PSBoundParameters.ContainsKey('toReplicate')) { $payload.toReplicate = $toReplicate; }
        if ($PSBoundParameters.ContainsKey('srvsize')) { $payload.srvsize = $srvsize; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "creating fog image";
        return (Add-FogTypeName -InputObject (New-FogObject -type object -coreObject image -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Image');
    }

}
