function Remove-FogStorageGroup {
    <#
    .SYNOPSIS
    Removes a storagegroup.

    .DESCRIPTION
    Deletes the storagegroup with the given id. The row is gone; FOG has no undo for this.

    .PARAMETER id
    The id of the storagegroup to remove. Accepts an id or an object with an id property, and binds from the pipeline.

    .EXAMPLE
    Remove-FogStorageGroup -id 1

    Removes storagegroup 1.

    Expected output:
    ""

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'deleteStoragegroup'
    (DELETE /storagegroup/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'storagegroup.delete' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        Write-Verbose "removing fog storagegroup $objectId";
        return Remove-FogObject -type object -coreObject storagegroup -IDofObject $objectId;
    }

}
