function Remove-FogSnapinGroupAssociation {
    <#
    .SYNOPSIS
    Removes a snapingroupassociation.

    .DESCRIPTION
    Deletes the snapingroupassociation with the given id. The row is gone; FOG has no undo for this.

    .PARAMETER id
    The id of the snapingroupassociation to remove. Accepts an id or an object with an id property, and binds from the pipeline.

    .EXAMPLE
    Remove-FogSnapinGroupAssociation -id 1

    Removes snapingroupassociation 1.

    Expected output:
    ""

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'deleteSnapingroupassociation'
    (DELETE /snapingroupassociation/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'snapin.delete' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        Write-Verbose "removing fog snapingroupassociation $objectId";
        return Remove-FogObject -type object -coreObject snapingroupassociation -IDofObject $objectId;
    }

}
