function Stop-FogScheduledTaskTask {
    <#
    .SYNOPSIS
    Cancels the active task on a scheduledtask.

    .DESCRIPTION
    Cancels whatever task is currently queued or running for the scheduledtask with the
    given id. Cancelling a task that is not there is not an error.

    .PARAMETER id
    The id of the scheduledtask whose task should be cancelled. Accepts an id or an object with an id property, and binds from the pipeline.

    .EXAMPLE
    Stop-FogScheduledTaskTask -id 1

    Cancels the active task on scheduledtask 1.

    Expected output:
    ""

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'cancelScheduledtask'
    (DELETE /scheduledtask/{id}/cancel) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'task.task' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [FogObjectRefTransform()]
        [Object]$id
    )

    process {
        Write-Verbose "cancelling the fog scheduledtask task on $id";
        return Remove-FogObject -type objecttasktype -coreTaskObject scheduledtask -IDofObject $id;
    }

}
