function Stop-FogGroupTask {
    <#
    .SYNOPSIS
    Cancels the active task on a group.

    .DESCRIPTION
    Cancels whatever task is currently queued or running for the group with the
    given id. Cancelling a task that is not there is not an error.

    .PARAMETER id
    The id of the group whose task should be cancelled. Accepts an id or an object with an id property, and binds from the pipeline.

    .EXAMPLE
    Stop-FogGroupTask -id 1

    Cancels the active task on group 1.

    Expected output:
    ""

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'cancelGroup'
    (DELETE /group/{id}/cancel) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'group.task' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [FogObjectRefTransform()]
        [Object]$id
    )

    process {
        Write-Verbose "cancelling the fog group task on $id";
        return Remove-FogObject -type objecttasktype -coreTaskObject group -IDofObject $id;
    }

}
