function Update-FogStorageNode {
    <#
    .SYNOPSIS
    Updates a storagenode.

    .DESCRIPTION
    Sends only the fields you name. FOG merges an edit into the existing row, so
    an unbound parameter is left alone rather than blanked -- which is why this
    builds its payload from $PSBoundParameters rather than from every parameter.

    .PARAMETER id
    The id of the storagenode to update. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    Sets the name field (column ngmMemberName). At most 250 characters.

    .PARAMETER description
    Sets the description field (column ngmMemberDescription).

    .PARAMETER isMaster
    Sets the isMaster field (column ngmIsMasterNode). At most 1 characters.

    .PARAMETER storagegroupID
    Sets the storagegroupID field (column ngmGroupID).

    .PARAMETER isEnabled
    Sets the isEnabled field (column ngmIsEnabled). At most 1 characters.

    .PARAMETER isGraphEnabled
    Sets the isGraphEnabled field (column ngmGraphEnabled).

    .PARAMETER path
    Sets the path field (column ngmRootPath).

    .PARAMETER ftppath
    Sets the ftppath field (column ngmFTPPath).

    .PARAMETER bitrate
    Sets the bitrate field (column ngmMaxBitrate). At most 25 characters.

    .PARAMETER helloInterval
    Sets the helloInterval field (column ngmHelloInterval). At most 8 characters.

    .PARAMETER snapinpath
    Sets the snapinpath field (column ngmSnapinPath).

    .PARAMETER sslpath
    Sets the sslpath field (column ngmSSLPath).

    .PARAMETER ip
    Sets the ip field (column ngmHostname). At most 250 characters.

    .PARAMETER maxClients
    Sets the maxClients field (column ngmMaxClients).

    .PARAMETER user
    Sets the user field (column ngmUser). At most 250 characters.

    .PARAMETER interface
    Sets the interface field (column ngmInterface). At most 25 characters.

    .PARAMETER bandwidth
    Sets the bandwidth field (column ngmBandwidthLimit).

    .PARAMETER webroot
    Sets the webroot field (column ngmWebroot).

    .PARAMETER graphcolor
    Sets the graphcolor field (column ngmGraphColor). At most 6 characters.

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters.

    .EXAMPLE
    Update-FogStorageNode -id 1 -name 'Updated'

    Updates the name of storagenode 1.

    Expected output:
    { "name": "Updated" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'updateStoragenode'
    (PUT /storagenode/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'storagenode.edit' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$isMaster,
        [Parameter()]
        [int]$storagegroupID,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$isEnabled,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$isGraphEnabled,
        [Parameter()]
        [string]$path,
        [Parameter()]
        [string]$ftppath,
        [Parameter()]
        [ValidateLength(0,25)]
        [string]$bitrate,
        [Parameter()]
        [ValidateLength(0,8)]
        [string]$helloInterval,
        [Parameter()]
        [string]$snapinpath,
        [Parameter()]
        [string]$sslpath,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$ip,
        [Parameter()]
        [int]$maxClients,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$user,
        [Parameter()]
        [ValidateLength(0,25)]
        [string]$interface,
        [Parameter()]
        [int]$bandwidth,
        [Parameter()]
        [string]$webroot,
        [Parameter()]
        [ValidateLength(0,6)]
        [string]$graphcolor,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('isMaster')) { $payload.isMaster = $isMaster; }
        if ($PSBoundParameters.ContainsKey('storagegroupID')) { $payload.storagegroupID = $storagegroupID; }
        if ($PSBoundParameters.ContainsKey('isEnabled')) { $payload.isEnabled = $isEnabled; }
        if ($PSBoundParameters.ContainsKey('isGraphEnabled')) { $payload.isGraphEnabled = $isGraphEnabled; }
        if ($PSBoundParameters.ContainsKey('path')) { $payload.path = $path; }
        if ($PSBoundParameters.ContainsKey('ftppath')) { $payload.ftppath = $ftppath; }
        if ($PSBoundParameters.ContainsKey('bitrate')) { $payload.bitrate = $bitrate; }
        if ($PSBoundParameters.ContainsKey('helloInterval')) { $payload.helloInterval = $helloInterval; }
        if ($PSBoundParameters.ContainsKey('snapinpath')) { $payload.snapinpath = $snapinpath; }
        if ($PSBoundParameters.ContainsKey('sslpath')) { $payload.sslpath = $sslpath; }
        if ($PSBoundParameters.ContainsKey('ip')) { $payload.ip = $ip; }
        if ($PSBoundParameters.ContainsKey('maxClients')) { $payload.maxClients = $maxClients; }
        if ($PSBoundParameters.ContainsKey('user')) { $payload.user = $user; }
        if ($PSBoundParameters.ContainsKey('interface')) { $payload.interface = $interface; }
        if ($PSBoundParameters.ContainsKey('bandwidth')) { $payload.bandwidth = $bandwidth; }
        if ($PSBoundParameters.ContainsKey('webroot')) { $payload.webroot = $webroot; }
        if ($PSBoundParameters.ContainsKey('graphcolor')) { $payload.graphcolor = $graphcolor; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "updating fog storagenode $objectId";
        return (Add-FogTypeName -InputObject (Update-FogObject -type object -coreObject storagenode -IDofObject $objectId -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Storagenode');
    }

}
