function Update-FogPrinter {
    <#
    .SYNOPSIS
    Updates a printer.

    .DESCRIPTION
    Sends only the fields you name. FOG merges an edit into the existing row, so
    an unbound parameter is left alone rather than blanked -- which is why this
    builds its payload from $PSBoundParameters rather than from every parameter.

    .PARAMETER id
    The id of the printer to update. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    Sets the name field (column pAlias). At most 250 characters.

    .PARAMETER description
    Sets the description field (column pDesc).

    .PARAMETER port
    Sets the port field (column pPort).

    .PARAMETER file
    Sets the file field (column pDefFile).

    .PARAMETER model
    Sets the model field (column pModel). At most 250 characters.

    .PARAMETER config
    Sets the config field (column pConfig). At most 10 characters.

    .PARAMETER configFile
    Sets the configFile field (column pConfigFile). At most 255 characters.

    .PARAMETER ip
    Sets the ip field (column pIP). At most 255 characters.

    .PARAMETER pAnon2
    Sets the pAnon2 field (column pAnon2). At most 10 characters.

    .PARAMETER pAnon3
    Sets the pAnon3 field (column pAnon3). At most 10 characters.

    .PARAMETER pAnon4
    Sets the pAnon4 field (column pAnon4). At most 10 characters.

    .PARAMETER pAnon5
    Sets the pAnon5 field (column pAnon5). At most 10 characters.

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters.

    .EXAMPLE
    Update-FogPrinter -id 1 -description 'Updated'

    Updates the description of printer 1.

    Expected output:
    { "id": 1, "description": "Updated" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'updatePrinter'
    (PUT /printer/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'printer.edit' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter()]
        [string]$port,
        [Parameter()]
        [string]$file,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$model,
        [Parameter()]
        [ValidateLength(0,10)]
        [string]$config,
        [Parameter()]
        [ValidateLength(0,255)]
        [string]$configFile,
        [Parameter()]
        [ValidateLength(0,255)]
        [string]$ip,
        [Parameter()]
        [ValidateLength(0,10)]
        [string]$pAnon2,
        [Parameter()]
        [ValidateLength(0,10)]
        [string]$pAnon3,
        [Parameter()]
        [ValidateLength(0,10)]
        [string]$pAnon4,
        [Parameter()]
        [ValidateLength(0,10)]
        [string]$pAnon5,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('port')) { $payload.port = $port; }
        if ($PSBoundParameters.ContainsKey('file')) { $payload.file = $file; }
        if ($PSBoundParameters.ContainsKey('model')) { $payload.model = $model; }
        if ($PSBoundParameters.ContainsKey('config')) { $payload.config = $config; }
        if ($PSBoundParameters.ContainsKey('configFile')) { $payload.configFile = $configFile; }
        if ($PSBoundParameters.ContainsKey('ip')) { $payload.ip = $ip; }
        if ($PSBoundParameters.ContainsKey('pAnon2')) { $payload.pAnon2 = $pAnon2; }
        if ($PSBoundParameters.ContainsKey('pAnon3')) { $payload.pAnon3 = $pAnon3; }
        if ($PSBoundParameters.ContainsKey('pAnon4')) { $payload.pAnon4 = $pAnon4; }
        if ($PSBoundParameters.ContainsKey('pAnon5')) { $payload.pAnon5 = $pAnon5; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "updating fog printer $objectId";
        return Update-FogObject -type object -coreObject printer -IDofObject $objectId -jsonData ($payload | ConvertTo-Json -Compress);
    }

}
