function Update-FogHost {
    <#
    .SYNOPSIS
    Updates a host.

    .DESCRIPTION
    Sends only the fields you name. FOG merges an edit into the existing row, so
    an unbound parameter is left alone rather than blanked -- which is why this
    builds its payload from $PSBoundParameters rather than from every parameter.

    .PARAMETER id
    The id of the host to update. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    Sets the name field (column hostName). At most 15 characters.

    .PARAMETER description
    Sets the description field (column hostDesc).

    .PARAMETER ip
    Sets the ip field (column hostIP). At most 25 characters.

    .PARAMETER imageID
    Sets the imageID field (column hostImage).

    .PARAMETER building
    Sets the building field (column hostBuilding).

    .PARAMETER deployed
    Sets the deployed field (column hostLastDeploy).

    .PARAMETER useAD
    Sets the useAD field (column hostUseAD). At most 1 characters.

    .PARAMETER ADDomain
    Sets the ADDomain field (column hostADDomain). At most 250 characters.

    .PARAMETER ADOU
    Sets the ADOU field (column hostADOU).

    .PARAMETER ADUser
    Sets the ADUser field (column hostADUser). At most 250 characters.

    .PARAMETER ADPass
    Sets the ADPass field (column hostADPass). At most 250 characters.

    .PARAMETER ADPassLegacy
    Sets the ADPassLegacy field (column hostADPassLegacy).

    .PARAMETER productKey
    Sets the productKey field (column hostProductKey).

    .PARAMETER printerLevel
    Sets the printerLevel field (column hostPrinterLevel). At most 2 characters.

    .PARAMETER kernelArgs
    Sets the kernelArgs field (column hostKernelArgs). At most 250 characters.

    .PARAMETER kernel
    Sets the kernel field (column hostKernel). At most 250 characters.

    .PARAMETER kernelDevice
    Sets the kernelDevice field (column hostDevice). At most 250 characters.

    .PARAMETER init
    Sets the init field (column hostInit).

    .PARAMETER pending
    Sets the pending field (column hostPending).

    .PARAMETER pingstatus
    Sets the pingstatus field (column hostPingCode). At most 20 characters.

    .PARAMETER pingmethod
    Sets the pingmethod field (column hostPingMethod). At most 10 characters.

    .PARAMETER lastping
    Sets the lastping field (column hostLastPing).

    .PARAMETER lastcheckin
    Sets the lastcheckin field (column hostLastCheckin).

    .PARAMETER biosexit
    Sets the biosexit field (column hostExitBios).

    .PARAMETER efiexit
    Sets the efiexit field (column hostExitEfi).

    .PARAMETER enforce
    Sets the enforce field (column hostEnforce).

    .PARAMETER tokenlock
    Sets the tokenlock field (column hostInfoLock).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters.

    .EXAMPLE
    Update-FogHost -id 1 -name 'Updated'

    Updates the name of host 1.

    Expected output:
    { "name": "Updated" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'updateHost'
    (PUT /host/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'host.edit' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter()]
        [ValidatePattern('^[A-Za-z0-9_!@#$%^()\-''{}.~]{1,15}$')]
        [Alias('hostName')]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter()]
        [ValidateLength(0,25)]
        [string]$ip,
        [Parameter()]
        [int]$imageID,
        [Parameter()]
        [int]$building,
        [Parameter()]
        [string]$deployed,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$useAD,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$ADDomain,
        [Parameter()]
        [string]$ADOU,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$ADUser,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$ADPass,
        [Parameter()]
        [string]$ADPassLegacy,
        [Parameter()]
        [string]$productKey,
        [Parameter()]
        [ValidateLength(0,2)]
        [string]$printerLevel,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$kernelArgs,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$kernel,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$kernelDevice,
        [Parameter()]
        [string]$init,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$pending,
        [Parameter()]
        [ValidateLength(0,20)]
        [string]$pingstatus,
        [Parameter()]
        [ValidateLength(0,10)]
        [string]$pingmethod,
        [Parameter()]
        [string]$lastping,
        [Parameter()]
        [string]$lastcheckin,
        [Parameter()]
        [string]$biosexit,
        [Parameter()]
        [string]$efiexit,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$enforce,
        [Parameter()]
        [int]$tokenlock,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('ip')) { $payload.ip = $ip; }
        if ($PSBoundParameters.ContainsKey('imageID')) { $payload.imageID = $imageID; }
        if ($PSBoundParameters.ContainsKey('building')) { $payload.building = $building; }
        if ($PSBoundParameters.ContainsKey('deployed')) { $payload.deployed = $deployed; }
        if ($PSBoundParameters.ContainsKey('useAD')) { $payload.useAD = $useAD; }
        if ($PSBoundParameters.ContainsKey('ADDomain')) { $payload.ADDomain = $ADDomain; }
        if ($PSBoundParameters.ContainsKey('ADOU')) { $payload.ADOU = $ADOU; }
        if ($PSBoundParameters.ContainsKey('ADUser')) { $payload.ADUser = $ADUser; }
        if ($PSBoundParameters.ContainsKey('ADPass')) { $payload.ADPass = $ADPass; }
        if ($PSBoundParameters.ContainsKey('ADPassLegacy')) { $payload.ADPassLegacy = $ADPassLegacy; }
        if ($PSBoundParameters.ContainsKey('productKey')) { $payload.productKey = $productKey; }
        if ($PSBoundParameters.ContainsKey('printerLevel')) { $payload.printerLevel = $printerLevel; }
        if ($PSBoundParameters.ContainsKey('kernelArgs')) { $payload.kernelArgs = $kernelArgs; }
        if ($PSBoundParameters.ContainsKey('kernel')) { $payload.kernel = $kernel; }
        if ($PSBoundParameters.ContainsKey('kernelDevice')) { $payload.kernelDevice = $kernelDevice; }
        if ($PSBoundParameters.ContainsKey('init')) { $payload.init = $init; }
        if ($PSBoundParameters.ContainsKey('pending')) { $payload.pending = $pending; }
        if ($PSBoundParameters.ContainsKey('pingstatus')) { $payload.pingstatus = $pingstatus; }
        if ($PSBoundParameters.ContainsKey('pingmethod')) { $payload.pingmethod = $pingmethod; }
        if ($PSBoundParameters.ContainsKey('lastping')) { $payload.lastping = $lastping; }
        if ($PSBoundParameters.ContainsKey('lastcheckin')) { $payload.lastcheckin = $lastcheckin; }
        if ($PSBoundParameters.ContainsKey('biosexit')) { $payload.biosexit = $biosexit; }
        if ($PSBoundParameters.ContainsKey('efiexit')) { $payload.efiexit = $efiexit; }
        if ($PSBoundParameters.ContainsKey('enforce')) { $payload.enforce = $enforce; }
        if ($PSBoundParameters.ContainsKey('tokenlock')) { $payload.tokenlock = $tokenlock; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "updating fog host $objectId";
        return (Add-FogTypeName -InputObject (Update-FogObject -type object -coreObject host -IDofObject $objectId -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Host');
    }

}
