function Update-FogSetting {
    <#
    .SYNOPSIS
    Updates a setting.

    .DESCRIPTION
    Sends only the fields you name. FOG merges an edit into the existing row, so
    an unbound parameter is left alone rather than blanked -- which is why this
    builds its payload from $PSBoundParameters rather than from every parameter.

    .PARAMETER id
    The id of the setting to update. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    Sets the name field (column settingKey). At most 255 characters.

    .PARAMETER description
    Sets the description field (column settingDesc).

    .PARAMETER value
    Sets the value field (column settingValue).

    .PARAMETER category
    Sets the category field (column settingCategory).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters.

    .EXAMPLE
    Update-FogSetting -id 1 -name 'Updated'

    Updates the name of setting 1.

    Expected output:
    { "name": "Updated" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'updateSetting'
    (PUT /setting/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'settings.edit' permission.
    #>

    [CmdletBinding()]
    [Alias('Set-FogSetting')]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter()]
        [ValidateLength(0,255)]
        [Alias('settingName')]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter()]
        [string]$value,
        [Parameter()]
        [string]$category,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('value')) { $payload.value = $value; }
        if ($PSBoundParameters.ContainsKey('category')) { $payload.category = $category; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "updating fog setting $objectId";
        return Update-FogObject -type object -coreObject setting -IDofObject $objectId -jsonData ($payload | ConvertTo-Json -Compress);
    }

}
