function Update-FogSnapin {
    <#
    .SYNOPSIS
    Updates a snapin.

    .DESCRIPTION
    Sends only the fields you name. FOG merges an edit into the existing row, so
    an unbound parameter is left alone rather than blanked -- which is why this
    builds its payload from $PSBoundParameters rather than from every parameter.

    .PARAMETER id
    The id of the snapin to update. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    Sets the name field (column sName). At most 200 characters.

    .PARAMETER description
    Sets the description field (column sDesc).

    .PARAMETER file
    Sets the file field (column sFilePath).

    .PARAMETER args
    Sets the args field (column sArgs).

    .PARAMETER reboot
    Sets the reboot field (column sReboot). At most 1 characters.

    .PARAMETER shutdown
    Sets the shutdown field (column sShutdown).

    .PARAMETER runWith
    Sets the runWith field (column sRunWith). At most 245 characters.

    .PARAMETER runWithArgs
    Sets the runWithArgs field (column sRunWithArgs). At most 200 characters.

    .PARAMETER protected
    Sets the protected field (column snapinProtect).

    .PARAMETER isEnabled
    Sets the isEnabled field (column sEnabled).

    .PARAMETER toReplicate
    Sets the toReplicate field (column sReplicate).

    .PARAMETER hide
    Sets the hide field (column sHideLog).

    .PARAMETER timeout
    Sets the timeout field (column sTimeout).

    .PARAMETER packtype
    Sets the packtype field (column sPackType).

    .PARAMETER hash
    Sets the hash field (column sHash). At most 255 characters.

    .PARAMETER size
    Sets the size field (column sSize).

    .PARAMETER anon3
    Sets the anon3 field (column sAnon3). At most 45 characters.

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters.

    .EXAMPLE
    Update-FogSnapin -id 1 -name 'Updated'

    Updates the name of snapin 1.

    Expected output:
    { "name": "Updated" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'updateSnapin'
    (PUT /snapin/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'snapin.edit' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter()]
        [ValidateLength(0,200)]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter()]
        [string]$file,
        [Parameter()]
        [string]$args,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$reboot,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$shutdown,
        [Parameter()]
        [ValidateLength(0,245)]
        [string]$runWith,
        [Parameter()]
        [ValidateLength(0,200)]
        [string]$runWithArgs,
        [Parameter()]
        [int]$protected,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$isEnabled,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$toReplicate,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$hide,
        [Parameter()]
        [int]$timeout,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$packtype,
        [Parameter()]
        [ValidateLength(0,255)]
        [string]$hash,
        [Parameter()]
        [int]$size,
        [Parameter()]
        [ValidateLength(0,45)]
        [string]$anon3,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('file')) { $payload.file = $file; }
        if ($PSBoundParameters.ContainsKey('args')) { $payload.args = $args; }
        if ($PSBoundParameters.ContainsKey('reboot')) { $payload.reboot = $reboot; }
        if ($PSBoundParameters.ContainsKey('shutdown')) { $payload.shutdown = $shutdown; }
        if ($PSBoundParameters.ContainsKey('runWith')) { $payload.runWith = $runWith; }
        if ($PSBoundParameters.ContainsKey('runWithArgs')) { $payload.runWithArgs = $runWithArgs; }
        if ($PSBoundParameters.ContainsKey('protected')) { $payload.protected = $protected; }
        if ($PSBoundParameters.ContainsKey('isEnabled')) { $payload.isEnabled = $isEnabled; }
        if ($PSBoundParameters.ContainsKey('toReplicate')) { $payload.toReplicate = $toReplicate; }
        if ($PSBoundParameters.ContainsKey('hide')) { $payload.hide = $hide; }
        if ($PSBoundParameters.ContainsKey('timeout')) { $payload.timeout = $timeout; }
        if ($PSBoundParameters.ContainsKey('packtype')) { $payload.packtype = $packtype; }
        if ($PSBoundParameters.ContainsKey('hash')) { $payload.hash = $hash; }
        if ($PSBoundParameters.ContainsKey('size')) { $payload.size = $size; }
        if ($PSBoundParameters.ContainsKey('anon3')) { $payload.anon3 = $anon3; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "updating fog snapin $objectId";
        return (Add-FogTypeName -InputObject (Update-FogObject -type object -coreObject snapin -IDofObject $objectId -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Snapin');
    }

}
