function Update-FogScheduledTask {
    <#
    .SYNOPSIS
    Updates a scheduledtask.

    .DESCRIPTION
    Sends only the fields you name. FOG merges an edit into the existing row, so
    an unbound parameter is left alone rather than blanked -- which is why this
    builds its payload from $PSBoundParameters rather than from every parameter.

    .PARAMETER id
    The id of the scheduledtask to update. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    Sets the name field (column stName). At most 240 characters.

    .PARAMETER description
    Sets the description field (column stDesc).

    .PARAMETER type
    Sets the type field (column stType). At most 24 characters.

    .PARAMETER taskTypeID
    Sets the taskTypeID field (column stTaskTypeID).

    .PARAMETER minute
    Sets the minute field (column stMinute). At most 240 characters.

    .PARAMETER hour
    Sets the hour field (column stHour). At most 240 characters.

    .PARAMETER dayOfMonth
    Sets the dayOfMonth field (column stDOM). At most 240 characters.

    .PARAMETER month
    Sets the month field (column stMonth). At most 240 characters.

    .PARAMETER dayOfWeek
    Sets the dayOfWeek field (column stDOW). At most 240 characters.

    .PARAMETER isGroupTask
    Sets the isGroupTask field (column stIsGroup). At most 2 characters.

    .PARAMETER hostID
    Sets the hostID field (column stGroupHostID).

    .PARAMETER shutdown
    Sets the shutdown field (column stShutDown). At most 2 characters.

    .PARAMETER other1
    Sets the other1 field (column stOther1). At most 240 characters.

    .PARAMETER other2
    Sets the other2 field (column stOther2). At most 240 characters.

    .PARAMETER other3
    Sets the other3 field (column stOther3). At most 240 characters.

    .PARAMETER other4
    Sets the other4 field (column stOther4). At most 240 characters.

    .PARAMETER other5
    Sets the other5 field (column stOther5). At most 240 characters.

    .PARAMETER scheduleTime
    Sets the scheduleTime field (column stDateTime).

    .PARAMETER isActive
    Sets the isActive field (column stActive). At most 2 characters.

    .PARAMETER imageID
    Sets the imageID field (column stImageID).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters.

    .EXAMPLE
    Update-FogScheduledTask -id 1 -name 'Updated'

    Updates the name of scheduledtask 1.

    Expected output:
    { "name": "Updated" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'updateScheduledtask'
    (PUT /scheduledtask/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'task.edit' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$name,
        [Parameter()]
        [string]$description,
        [Parameter()]
        [ValidateLength(0,24)]
        [string]$type,
        [Parameter()]
        [int]$taskTypeID,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$minute,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$hour,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$dayOfMonth,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$month,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$dayOfWeek,
        [Parameter()]
        [ValidateLength(0,2)]
        [string]$isGroupTask,
        [Parameter()]
        [int]$hostID,
        [Parameter()]
        [ValidateLength(0,2)]
        [string]$shutdown,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other1,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other2,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other3,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other4,
        [Parameter()]
        [ValidateLength(0,240)]
        [string]$other5,
        [Parameter()]
        [int]$scheduleTime,
        [Parameter()]
        [ValidateLength(0,2)]
        [string]$isActive,
        [Parameter()]
        [int]$imageID,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('description')) { $payload.description = $description; }
        if ($PSBoundParameters.ContainsKey('type')) { $payload.type = $type; }
        if ($PSBoundParameters.ContainsKey('taskTypeID')) { $payload.taskTypeID = $taskTypeID; }
        if ($PSBoundParameters.ContainsKey('minute')) { $payload.minute = $minute; }
        if ($PSBoundParameters.ContainsKey('hour')) { $payload.hour = $hour; }
        if ($PSBoundParameters.ContainsKey('dayOfMonth')) { $payload.dayOfMonth = $dayOfMonth; }
        if ($PSBoundParameters.ContainsKey('month')) { $payload.month = $month; }
        if ($PSBoundParameters.ContainsKey('dayOfWeek')) { $payload.dayOfWeek = $dayOfWeek; }
        if ($PSBoundParameters.ContainsKey('isGroupTask')) { $payload.isGroupTask = $isGroupTask; }
        if ($PSBoundParameters.ContainsKey('hostID')) { $payload.hostID = $hostID; }
        if ($PSBoundParameters.ContainsKey('shutdown')) { $payload.shutdown = $shutdown; }
        if ($PSBoundParameters.ContainsKey('other1')) { $payload.other1 = $other1; }
        if ($PSBoundParameters.ContainsKey('other2')) { $payload.other2 = $other2; }
        if ($PSBoundParameters.ContainsKey('other3')) { $payload.other3 = $other3; }
        if ($PSBoundParameters.ContainsKey('other4')) { $payload.other4 = $other4; }
        if ($PSBoundParameters.ContainsKey('other5')) { $payload.other5 = $other5; }
        if ($PSBoundParameters.ContainsKey('scheduleTime')) { $payload.scheduleTime = $scheduleTime; }
        if ($PSBoundParameters.ContainsKey('isActive')) { $payload.isActive = $isActive; }
        if ($PSBoundParameters.ContainsKey('imageID')) { $payload.imageID = $imageID; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "updating fog scheduledtask $objectId";
        return (Add-FogTypeName -InputObject (Update-FogObject -type object -coreObject scheduledtask -IDofObject $objectId -jsonData ($payload | ConvertTo-Json -Compress)) -TypeName 'FogApi.Scheduledtask');
    }

}
