function Update-FogTask {
    <#
    .SYNOPSIS
    Updates a task.

    .DESCRIPTION
    Sends only the fields you name. FOG merges an edit into the existing row, so
    an unbound parameter is left alone rather than blanked -- which is why this
    builds its payload from $PSBoundParameters rather than from every parameter.

    .PARAMETER id
    The id of the task to update. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    Sets the name field (column taskName). At most 250 characters.

    .PARAMETER checkInTime
    Sets the checkInTime field (column taskCheckIn).

    .PARAMETER hostID
    Sets the hostID field (column taskHostID).

    .PARAMETER stateID
    Sets the stateID field (column taskStateID).

    .PARAMETER isForced
    Sets the isForced field (column taskForce). At most 1 characters.

    .PARAMETER scheduledStartTime
    Sets the scheduledStartTime field (column taskScheduledStartTime).

    .PARAMETER typeID
    Sets the typeID field (column taskTypeID).

    .PARAMETER storagegroupID
    Sets the storagegroupID field (column taskNFSGroupID).

    .PARAMETER storagenodeID
    Sets the storagenodeID field (column taskNFSMemberID).

    .PARAMETER NFSFailures
    Sets the NFSFailures field (column taskNFSFailures). At most 1 characters.

    .PARAMETER NFSLastMemberID
    Sets the NFSLastMemberID field (column taskLastMemberID).

    .PARAMETER shutdown
    Sets the shutdown field (column taskShutdown). At most 1 characters.

    .PARAMETER passreset
    Sets the passreset field (column taskPassreset). At most 250 characters.

    .PARAMETER isDebug
    Sets the isDebug field (column taskIsDebug).

    .PARAMETER imageID
    Sets the imageID field (column taskImageID).

    .PARAMETER wol
    Sets the wol field (column taskWOL).

    .PARAMETER bypassbitlocker
    Sets the bypassbitlocker field (column taskBypassBitlocker).

    .PARAMETER stateChangedTime
    Sets the stateChangedTime field (column taskStateChangedTime).

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters.

    .EXAMPLE
    Update-FogTask -id 1 -name 'Updated'

    Updates the name of task 1.

    Expected output:
    { "name": "Updated" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'updateTask'
    (PUT /task/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'task.edit' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$name,
        [Parameter()]
        [string]$checkInTime,
        [Parameter()]
        [int]$hostID,
        [Parameter()]
        [int]$stateID,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$isForced,
        [Parameter()]
        [string]$scheduledStartTime,
        [Parameter()]
        [int]$typeID,
        [Parameter()]
        [int]$storagegroupID,
        [Parameter()]
        [int]$storagenodeID,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$NFSFailures,
        [Parameter()]
        [int]$NFSLastMemberID,
        [Parameter()]
        [ValidateLength(0,1)]
        [string]$shutdown,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$passreset,
        [Parameter()]
        [int]$isDebug,
        [Parameter()]
        [int]$imageID,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$wol,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$bypassbitlocker,
        [Parameter()]
        [string]$stateChangedTime,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('checkInTime')) { $payload.checkInTime = $checkInTime; }
        if ($PSBoundParameters.ContainsKey('hostID')) { $payload.hostID = $hostID; }
        if ($PSBoundParameters.ContainsKey('stateID')) { $payload.stateID = $stateID; }
        if ($PSBoundParameters.ContainsKey('isForced')) { $payload.isForced = $isForced; }
        if ($PSBoundParameters.ContainsKey('scheduledStartTime')) { $payload.scheduledStartTime = $scheduledStartTime; }
        if ($PSBoundParameters.ContainsKey('typeID')) { $payload.typeID = $typeID; }
        if ($PSBoundParameters.ContainsKey('storagegroupID')) { $payload.storagegroupID = $storagegroupID; }
        if ($PSBoundParameters.ContainsKey('storagenodeID')) { $payload.storagenodeID = $storagenodeID; }
        if ($PSBoundParameters.ContainsKey('NFSFailures')) { $payload.NFSFailures = $NFSFailures; }
        if ($PSBoundParameters.ContainsKey('NFSLastMemberID')) { $payload.NFSLastMemberID = $NFSLastMemberID; }
        if ($PSBoundParameters.ContainsKey('shutdown')) { $payload.shutdown = $shutdown; }
        if ($PSBoundParameters.ContainsKey('passreset')) { $payload.passreset = $passreset; }
        if ($PSBoundParameters.ContainsKey('isDebug')) { $payload.isDebug = $isDebug; }
        if ($PSBoundParameters.ContainsKey('imageID')) { $payload.imageID = $imageID; }
        if ($PSBoundParameters.ContainsKey('wol')) { $payload.wol = $wol; }
        if ($PSBoundParameters.ContainsKey('bypassbitlocker')) { $payload.bypassbitlocker = $bypassbitlocker; }
        if ($PSBoundParameters.ContainsKey('stateChangedTime')) { $payload.stateChangedTime = $stateChangedTime; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "updating fog task $objectId";
        return Update-FogObject -type object -coreObject task -IDofObject $objectId -jsonData ($payload | ConvertTo-Json -Compress);
    }

}
