function Update-FogMulticastSession {
    <#
    .SYNOPSIS
    Updates a multicastsession.

    .DESCRIPTION
    Sends only the fields you name. FOG merges an edit into the existing row, so
    an unbound parameter is left alone rather than blanked -- which is why this
    builds its payload from $PSBoundParameters rather than from every parameter.

    .PARAMETER id
    The id of the multicastsession to update. Accepts an id or an object with an id property, and binds from the pipeline.

    .PARAMETER name
    Sets the name field (column msName). At most 250 characters.

    .PARAMETER port
    Sets the port field (column msBasePort).

    .PARAMETER logpath
    Sets the logpath field (column msLogPath).

    .PARAMETER image
    Sets the image field (column msImage).

    .PARAMETER clients
    Sets the clients field (column msClients).

    .PARAMETER sessclients
    Sets the sessclients field (column msSessClients).

    .PARAMETER interface
    Sets the interface field (column msInterface). At most 250 characters.

    .PARAMETER starttime
    Sets the starttime field (column msStartDateTime).

    .PARAMETER percent
    Sets the percent field (column msPercent).

    .PARAMETER stateID
    Sets the stateID field (column msState).

    .PARAMETER completetime
    Sets the completetime field (column msCompleteDateTime).

    .PARAMETER isDD
    Sets the isDD field (column msIsDD).

    .PARAMETER storagegroupID
    Sets the storagegroupID field (column msNFSGroupID).

    .PARAMETER shutdown
    Sets the shutdown field (column msShutdown).

    .PARAMETER maxwait
    Sets the maxwait field (column msMaxwait).

    .PARAMETER senderpid
    Sets the senderpid field (column msSenderPID).

    .PARAMETER sendernode
    Sets the sendernode field (column msSenderNode).

    .PARAMETER senderstart
    Sets the senderstart field (column msSenderStart).

    .PARAMETER anon5
    Sets the anon5 field (column msAnon5). At most 250 characters.

    .PARAMETER settings
    A hashtable of raw field values, merged over the named parameters.

    .EXAMPLE
    Update-FogMulticastSession -id 1 -name 'Updated'

    Updates the name of multicastsession 1.

    Expected output:
    { "name": "Updated" }

    .NOTES
    Generated by spec/tools/New-FogApiFunctionFile.ps1 from operation 'updateMulticastsession'
    (PUT /multicastsession/{id}) in spec/fog-api-spec.json. Edit the spec, not this file.
    Requires the 'task.edit' permission.
    #>

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
        [Alias('IDofObject')]
        [Object]$id,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$name,
        [Parameter()]
        [int]$port,
        [Parameter()]
        [string]$logpath,
        [Parameter()]
        [string]$image,
        [Parameter()]
        [int]$clients,
        [Parameter()]
        [int]$sessclients,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$interface,
        [Parameter()]
        [string]$starttime,
        [Parameter()]
        [int]$percent,
        [Parameter()]
        [int]$stateID,
        [Parameter()]
        [string]$completetime,
        [Parameter()]
        [int]$isDD,
        [Parameter()]
        [int]$storagegroupID,
        [Parameter()]
        [ValidateSet('0','1')]
        [string]$shutdown,
        [Parameter()]
        [int]$maxwait,
        [Parameter()]
        [int]$senderpid,
        [Parameter()]
        [int]$sendernode,
        [Parameter()]
        [string]$senderstart,
        [Parameter()]
        [ValidateLength(0,250)]
        [string]$anon5,
        [Parameter()]
        [hashtable]$settings
    )

    process {
        $objectId = if ($id -is [System.Management.Automation.PSObject] -and $id.PSObject.Properties.Name -contains 'id') { $id.id } else { $id };
        $payload = @{};
        if ($PSBoundParameters.ContainsKey('name')) { $payload.name = $name; }
        if ($PSBoundParameters.ContainsKey('port')) { $payload.port = $port; }
        if ($PSBoundParameters.ContainsKey('logpath')) { $payload.logpath = $logpath; }
        if ($PSBoundParameters.ContainsKey('image')) { $payload.image = $image; }
        if ($PSBoundParameters.ContainsKey('clients')) { $payload.clients = $clients; }
        if ($PSBoundParameters.ContainsKey('sessclients')) { $payload.sessclients = $sessclients; }
        if ($PSBoundParameters.ContainsKey('interface')) { $payload.interface = $interface; }
        if ($PSBoundParameters.ContainsKey('starttime')) { $payload.starttime = $starttime; }
        if ($PSBoundParameters.ContainsKey('percent')) { $payload.percent = $percent; }
        if ($PSBoundParameters.ContainsKey('stateID')) { $payload.stateID = $stateID; }
        if ($PSBoundParameters.ContainsKey('completetime')) { $payload.completetime = $completetime; }
        if ($PSBoundParameters.ContainsKey('isDD')) { $payload.isDD = $isDD; }
        if ($PSBoundParameters.ContainsKey('storagegroupID')) { $payload.storagegroupID = $storagegroupID; }
        if ($PSBoundParameters.ContainsKey('shutdown')) { $payload.shutdown = $shutdown; }
        if ($PSBoundParameters.ContainsKey('maxwait')) { $payload.maxwait = $maxwait; }
        if ($PSBoundParameters.ContainsKey('senderpid')) { $payload.senderpid = $senderpid; }
        if ($PSBoundParameters.ContainsKey('sendernode')) { $payload.sendernode = $sendernode; }
        if ($PSBoundParameters.ContainsKey('senderstart')) { $payload.senderstart = $senderstart; }
        if ($PSBoundParameters.ContainsKey('anon5')) { $payload.anon5 = $anon5; }
        # -settings wins, so a caller can reach a field this module does not
        # model yet without the named parameters fighting them for it.
        if ($PSBoundParameters.ContainsKey('settings')) {
            foreach ($key in $settings.Keys) { $payload[$key] = $settings[$key]; }
        }
        Write-Verbose "updating fog multicastsession $objectId";
        return Update-FogObject -type object -coreObject multicastsession -IDofObject $objectId -jsonData ($payload | ConvertTo-Json -Compress);
    }

}
