name: Tag, Release, and Publish to Gallery

on:
  workflow_dispatch:

jobs:

  run-build-test:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Run the build test workflow
        run: gh workflow run build-test.yml
        env:
          GH_TOKEN: ${{ github.token }}

  confirm-build-test:
    needs: run-build-test
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Wait for the runs to start
        run: start-sleep 60

      - name: Get run IDs
        run: |
          $runid=((& gh run list --workflow build-test.yml --json databaseId --limit 1) | convertfrom-json).databaseId
          echo "RUNID=$runid" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    
      - name: confirm build didn't fail
        run: |
          $runstatus=""
          while (($runstatus -ne "success") -AND ($runstatus -ne "failure")) {
              start-sleep 15
              $runstatus=((& gh run view $env:RUNID --exit-status --json conclusion) | Convertfrom-json).conclusion
          }    
          if ($runstatus -eq "failure") {
              exit 1
          } else { 
              exit 0
          }

  publish-built-module:
      needs: confirm-build-test
      runs-on: windows-latest
      steps:
        - name: test
          run: echo 'build success!'
        
    
